### ISSUE TITLE
FreeType Development missing, but installed

### ISSUE THREAD

**Issue by sadkris** [AndreRH/hangover#101]
## System Details

aarch64 Debian 10
clang
clang version 7.0.1-8+deb10u2 (tags/RELEASE_701/final)

## Problems Description

FreeType throws back an error on wine compilation stating I'm missing the packages, when I have all the development libraries and normal FreeType packages installed. I installed libwine as well to make sure I wasn't missing anything, to find the same problem with the following error:

configure: error: FreeType development files not found. Fonts will not be built.
Use the --without-freetype option if you really want this.
make: *** [Makefile:147: build/wine-host/Makefile] Error 1

**Comment by stefand** [comment]
have a look at config.log . It should give you the test program configure is trying to compile and what fails. Maybe some headers are in an unexpected location?

**Comment by sadkris** [comment]
Sorry I never updated this, the solution was pretty fairly random so I'll document it. I had to run the following commands:
`xhost +`
This basically allowed programs to interface with the x11, nice.
`software-properties-gtk`
Using x11 this command opens a window for software properties. With this open, you should set the Source Code option to add the item to your sources list, and hit refresh when it asks. This allows Debian to view the dependencies for packages.
`sudo apt build-dep wine64`
This installs all the missing dependencies for wine, including the missing package.
