### ISSUE TITLE
Run MFC App with a weird messagebox and then terminated

### ISSUE THREAD

**Issue by Iamnvincible** [AndreRH/hangover#102]
## System Details

Running on ARM64

Compiled on ARM64

toolchain
clang 7.0.1-8+deb10u2

## Problems Description

The building process is successful.
I have two old MFC  apps, one app runs pretty good and the other one terminated  with a message box reads "Windows ????????".
I have hacked the binary of the app, and there is no call for messageboxA with such text.
So I think the prompt is not from the app.
![2021-01-12_10-58](https://user-images.githubusercontent.com/5810474/104263744-24f10d80-54c5-11eb-87d3-2338b7844764.png)
The captions of the apps are Chinese , some UI text displayed well while others displayed with '?' , that'
s weird.
I am not experienced with win32 development, I guess the prompt is from wine itself, but I can not find any vestige
from wine's source code.
I have struggled for days, I would appreciate it very much  if you can offer me a hand.

**Comment by AndreRH** [comment]
Something in the logs?

**Comment by Iamnvincible** [comment]
> Something in the logs?

Default output shows below.
The message box shows after the last line of log,.
```
32 bit environment set up, Large Address Aware: NO.
0024:fixme:qemu_ntdll:qemu_RtlAddVectoredExceptionHandler Unverified!
0024:fixme:qemu_kernel32:qemu_GetPrivateProfileIntA Unverified!
0024:fixme:qemu_kernel32:qemu_GetPrivateProfileIntA Unverified!
0024:fixme:qemu_kernel32:qemu_GetProcessVersion Unverified!
0024:fixme:qemu_kernel32:qemu_OutputDebugStringA Unverified!
0024:err:winediag:ODBC_LoadDriverManager failed to open library "libodbc.dll": No dlopen support on Windows
0024:fixme:qemu_kernel32:qemu_OutputDebugStringA Unverified!
0024:fixme:qemu_kernel32:qemu_OutputDebugStringA Unverified!
0024:fixme:qemu_kernel32:qemu_OutputDebugStringA Unverified!
0024:err:qemu_user32:set_windows_hook Hook proc 0x5f43b7f6, host proc 0x7ffffe470010
0024:fixme:qemu_user32:set_windows_hook (WH_MSGFILTER, 0x5f43b7f6, 0x0, 24, 0).
```
