### ISSUE TITLE
No wine64, but wine

### ISSUE THREAD

**Issue by HoSnoopy** [AndreRH/hangover#105]
## System Details

Raspberry Pi / arm64 
also for compiling 
with the debian-standard packages as neccesary 

## Problems Description

Started "make" as descibed in issue #84

At the end, make worked, but I cannot find wine64, only wine. I Also tried it with the --win64-flag, but then I get the error in #84.

I want to start a win32.exe and there I get the error "Windows sockets initialization failed."
in the shell this came:
 0074:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
32 bit environment set up, Large Address Aware: NO.
0024:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.erf imported from L"C:\\windows\\system32\\gdiplus.dll", setting to 0x7faded2105
0024:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.fmax imported from L"C:\\windows\\system32\\gdiplus.dll", setting to 0x7faded2105
0024:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.fmin imported from L"C:\\windows\\system32\\gdiplus.dll", setting to 0x7faded2105
0024:fixme:qemu_module:import_dll No implementation for kernel32.dll.K32GetWsChangesEx imported from L"C:\\windows\\system32\\PSAPI.DLL", setting to 0x7faded2105
0024:fixme:qemu_ntdll:qemu_RtlAddVectoredExceptionHandler Unverified!
0024:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0024:err:qemu_user32:set_windows_hook Hook proc 0x49c5aa, host proc 0x7f9ded0010
0024:fixme:qemu_user32:set_windows_hook (WH_MSGFILTER, 0x49c5aa, 0x0, 24, 1).
0024:fixme:qemu_kernel32:qemu_GetVolumeInformationW Unverified!
wine: Read access denied for device L"\\??\\E:\\", FS volume label and serial are not available.

On wine32 on a amd64-system it works.

**Comment by AndreRH** [comment]
So what you did is:
HANGOVER_WINE_CC=clang HANGOVER_WINE_CXX=clang++ make
?
Without any modifications?
Then I can't imagine how you would get a wine-host without wine64...
Which git commit are you trying to build?

**Comment by stefand** [comment]
We don't build a --enable-win64 wine on arm64 any more. Because ARM wine doesn't do any sort of multilib on non-x86 --enable-win64 is wrong on non-x86 platforms.

I believe your issue is unrelated to wine vs wine64 and may be due to limits in hangover's wrapper libs. I don't see anything obvious in the standard debug output though.

**Comment by HoSnoopy** [comment]
Thanks! got it! :) I hope in future it maybe works..

**Comment by stefand** [comment]
It'd be helpful to know which application you are tryting to run

**Comment by HoSnoopy** [comment]
https://sbc-support.com/uploads/tx_srcproducts/SBC_MicroBrowser_V147_5.zip <- This one. You have to register and get a licence for all functions, but for testing/only starting not.

**Comment by AndreRH** [comment]
It's wine (without 64) now in every case for Hangover
