### ISSUE TITLE
WoW64 Supported ?

### ISSUE THREAD

**Issue by liberodark** [AndreRH/hangover#108]
Hi,

If i want to compile hangover same as wine with wow64.
Is possible and supported ?

Best Regards

**Comment by frankwalter1301** [comment]
No atm

**Comment by AndreRH** [comment]
There's initial work here: https://github.com/AndreRH/hangover/tree/hangover-next
But it's not ready yet, but is likely to progress until end of the year

**Comment by AndreRH** [comment]
master branch was updated
