### ISSUE TITLE
Sound is missing in hangover

### ISSUE THREAD

**Issue by daemongloom** [AndreRH/hangover#117]
## System Details

Lenovo Chromebook Duet, crostini vm, Debian 10.

I've tried with hangover built via docker on that machine myself and Devedse's prebuilt versions

## Problems Description

I've tried to launch old Marble Drop game (https://archive.org/details/marble-drop). It worked fine, but there was no sound.
The same happened with putty.
Error in log is
`00c8:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
00c8:err:ole:com_get_class_object no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1`

Can't check winecfg's Audio tab as it dies with error.
`0024:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vswprintf_s imported from L"C:\\windows\\system32\\oleaut32.dll", setting to 0x74b9bf9705`

Audio from that vm works fine, I've checked it with vlc. 

Am I missing something in my setup? Any ways/tests to do to fix audio?

**Comment by stefand** [comment]
See if sound works in arm64 winecfg (not run inside hangover).

It is quite possible that our mmdevapi wrapper is missing some interfaces added in later Wine versions. Although I am curious why such an old game would go through the mmdevapi wrapper. I'd expect it to use either dsound or winmm, both of which are wrapped right away and then the arm64 DLLs call arm64 mmdevapi.

**Comment by daemongloom** [comment]
![Screenshot 2021-04-20 20 54 43](https://user-images.githubusercontent.com/3511755/115427237-ba194600-a21a-11eb-80ab-6fa62e928c4b.png)
Wine from Debian 10 works fine. Audio tab in winecfg is working and test button plays sound successfully.

**Comment by stefand** [comment]
Use the same wine that you use to run hangover, not the one from the package repos. It could be that the hangover build is missing winepulse.drv.so for example. Just don't run the x86 winecfg, run the arm one.

**Comment by daemongloom** [comment]
I've launched /usr/lib/aarch64-linux-gnu/wine/fakedlls/winecfg.exe with hangover's wine. Audio tab was working, but there are no audio devices listed. "Test sound" button produces following error: 
`002c:err:process:NtCreateUserProcess L"\\??\\C:\\windows\\syswow64\\rundll32.exe" not supported on this installation (x86 binary)
wine: configuration in L"/home/daemongloom/.wine" has been updated.
0024:err:mmdevapi:DllGetClassObject Driver initialization failed
0024:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
0024:err:ole:com_get_class_object no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
00fc:err:mmdevapi:DllGetClassObject Driver initialization failed`

**Comment by stefand** [comment]
Ah that suggests that Devedse's docker container build is missing audio backends. Presumably because they don't care about audio for their image processing programs.

You can try to build yourself (it's not trivial unfortunately) or try to run qemu.exe.so with Debian's Wine (there are some hacks in hangover's Wine for edge cases, but it might run your game with sound)

**Comment by daemongloom** [comment]
> Ah that suggests that Devedse's docker container build is missing audio backends. Presumably because they don't care about audio for their image processing programs.

There is also no winepulse.drv.so in docker-based build of hangover. I've built it on 1st of March, so it is not very old one.

**Comment by stefand** [comment]
Check the output of Wine's configure (the one in build/wine-host). It will warn about missing libraries - presumably you need something along the name libpulse and libpulse-dev or so. I am not a Debian user, so I don't know the exact names.

wine-hosts configure invocation in the top level Makefile is pretty simple: It is just

../../wine/configure

On x86_64 the top level Makefile adds --enable-win64, but that's specific to this platform. Oh, and it also points to a separate wine-tools build directory, but that only matters for cross compiling.

**Comment by daemongloom** [comment]
That's the problem. I used docker for building hangover because installing all dependencies on debian 10 is a pain. As it has very old software versions in repos.
I'll try to check it tomorrow when there is enough time to do a complete new build.

**Comment by daemongloom** [comment]
I've added libpulse-dev to docker file.
Hangover's winecfg dies when switching to audio tab.
ARM64 winecfg shows audio tab, there is pulseaudio device, "Test" button plays sound successfully.
Putty plays .wav file from game successfully.

But game shows following error:
`0024:err:pulse:pulse_test_connect Failed to create context
0024:err:mmdevapi:DllGetClassObject Driver initialization failed
0024:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
0024:err:ole:com_get_class_object no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
0024:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005`
Any additional packages that I have to add?

**Comment by stefand** [comment]
> 0024:err:pulse:pulse_test_connect Failed to create context

This is where the problem is, and it is a nasty issue. hangover is rather inefficient re address space (qemu allocs, wrapper libs, the JIT translated code, etc) and pulseaudio thinks it is running in a 64 bit process so it can map a huge shared memory blob into the process to transfer data between the client process and pulseaudio server.

Most old Win32 applications have just 2 GB address space available. While there is certainly room for PA's shm allocation in there by size, by the time the application tries to play sound the 2 GB are fragmented enough that PA can't place its shm area anywhere. I think for 64 bit processes it defaults to 256 mb nowadays, because why not, address space is free...

https://manpages.debian.org/testing/pulseaudio/pulse-client.conf.5.en.html enable-shm, shm-size-bytes. You can also try to edit qemu/windows-user/main.c to set large_address_aware to always true to have qemu keep a full 4 gb address space available. But that might break your app.

**Comment by devedse** [comment]
My fork indeed shouldn't have changed anything to the actual docker builds, I only changed the pipeline so that it creates an automatic release with every checkin.

This allows me to easily do a `wget -O /root/buildfolder_build_arm64.tar.gz --no-verbose https://github.com/devedse/hangover/releases/latest/download/buildfolder_build_arm64.tar.gz` to get the latest hangover release.

(It doesn't seem to be possible to do a `latest` wget on the actual build output)

**Comment by daemongloom** [comment]
I've built hangover without docker - it behaves exactly the same way as docker-built one (with added libpulse-dev).
Log is the same as in my post https://github.com/AndreRH/hangover/issues/117#issuecomment-823798834

I've tried to enable-shm =yes and shm-size-bytes = 4194304 {that's 4MB}. It gives a bit different log:
```
starting L"/home/daemongloom/.wine/drive_c/Marble/marble.exe" with Hangover

0024:err:secur32:SECUR32_initSchannelSP TLS library not found, SSL connections will fail
32 bit environment set up, Large Address Aware: NO.
0024:fixme:qemu_ntdll:qemu_RtlAddVectoredExceptionHandler Unverified!
0024:fixme:qemu_kernel32:qemu_GetPrivateProfileSectionW Unverified!
0024:fixme:qemu_kernel32:qemu_GetEnvironmentStringsA Unverified!
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:mciavi:MCIAVI_mciRealize (0002, 00000000, 000000000022CF50) : stub
0024:fixme:mciavi:MCIAVI_mciRealize (0002, 00000000, 000000000022CF50) : stub
mmap() failed: Cannot allocate memory
Failed to create permanent mapping for memfd region with ID = 2849542420
mmap() failed: Cannot allocate memory
Failed to create permanent mapping for memfd region with ID = 2279003944
Ignoring received block reference with non-registered memfd ID = 2279003944
00c4:err:mmdevapi:DllGetClassObject Driver initialization failed
00c4:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
00c4:err:ole:com_get_class_object no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
0024:fixme:bitmap:CreateBitmapIndirect planes = 0
mmap() failed: Cannot allocate memory
Failed to create permanent mapping for memfd region with ID = 2849542420
mmap() failed: Cannot allocate memory
Failed to create permanent mapping for memfd region with ID = 2108268435
Ignoring received block reference with non-registered memfd ID = 2108268435
0024:err:mmdevapi:DllGetClassObject Driver initialization failed
0024:err:ole:apartment_getclassobject DllGetClassObject returned error 0x80004005 for dll L"C:\\windows\\system32\\mmdevapi.dll"
0024:err:ole:com_get_class_object no class object {bcde0395-e52f-467c-8e3d-c4579291692e} could be created for context 0x1
0024:err:dsound:get_mmdevenum CoCreateInstance failed: 80004005
0024:fixme:qemu_gdi32:qemu_SetSystemPaletteUse Unverified!
0024:fixme:qemu_gdi32:qemu_SetSystemPaletteUse Unverified!
0024:fixme:qemu_gdi32:qemu_ResizePalette Unverified!
```

I'll try editing qemu now.

**Comment by AndreRH** [comment]
Sound should not be an issue anymore, open new issues in case there's some trouble
