### ISSUE TITLE
wine: could not locate the Wine build tree

### ISSUE THREAD

**Issue by kingsman-star** [AndreRH/hangover#118]
How to fix this?

root@kali:~/hangover# build/wine-guest64/wine                     
wine: could not locate the Wine build tree

**Comment by AndreRH** [comment]
see https://github.com/AndreRH/hangover#5-how-to-run

**Comment by kingsman-star** [comment]
oh sorry. I was wrong when I typed the command and didn't realize it. thanks 👍
