### ISSUE TITLE
Assertion failed: (view->protect & VPROT_SYSTEM), function create_view, file virtual.c, line 1500.

### ISSUE THREAD

**Issue by VisualEhrmanntraut** [AndreRH/hangover#124]
## System Details

What platform are you running on? x86_64 macOS Monterey 12.0.1 (21A559)
What platform did you use for compilation? x86_64 macOS Monterey 12.0.1 (21A559)
Toolchain details:
x86_64-w64-mingw32-gcc --version                                                                                                                                    
x86_64-w64-mingw32-gcc (GCC) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Installed via `brew install mingw-w64`

## Problems Description

What exactly did you do? Run a command line application like
```
build/wine-host/loader/wine64 /Users/visual/Downloads/ptr2besms/ws/ptr2bes.exe
```
Program fails to run with the following output:
```
wine: Unhandled page fault on read access to 0000000000000000 at address 00000003AF6D4A30 (thread 002c), starting debugger...
002c:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 40 48" (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger

starting L"/Users/visual/Downloads/ptr2besms/ws/ptr2bes.exe" with Hangover

0034:fixme:font:opentype_enum_font_names handle name format 1
0024:fixme:font:opentype_enum_font_names handle name format 1
Assertion failed: (view->protect & VPROT_SYSTEM), function create_view, file virtual.c, line 1500.
wine: Assertion failed at address 00007FF813681112 (thread 0024), starting debugger...
0024:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 32 104" (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger
```
Have you read #84? Unrelated, on x86_64

**Comment by AndreRH** [comment]
Please try again with Hangover 9.x and open a new issue
