### ISSUE TITLE
libiconv fails

### ISSUE THREAD

**Issue by alectries** [AndreRH/hangover#127]
Building hangover on Debian 11.2 arm64, fails during make with error:

libtool: compile:  clang -I. -I../../../libiconv/lib -I../include -I../../../libiconv/lib/../include -I.. -I../../../libiconv/lib/.. -I/usr/local/include -fvisibility=hidden -DLIBDIR=\"/home/alec/git/hangover/build/x86_64-w64-mingw32/lib\" -DBUILDING_LIBICONV -DBUILDING_DLL -DENABLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/home/alec/git/hangover/build/x86_64-w64-mingw32/lib\" -DNO_XMALLOC -Dset_relocation_prefix=libiconv_set_relocation_prefix -Drelocate=libiconv_relocate -Drelocate2=libiconv_relocate2 -DHAVE_CONFIG_H -c ../../../libiconv/lib/relocatable.c -o relocatable.o
/bin/bash ../libtool --mode=compile --tag=RC  `/bin/bash ../../../libiconv/lib/../windows/windres-options --escape 1.16` -i ../../../libiconv/lib/../windows/libiconv.rc -o libiconv.res.lo --output-format=coff
Usage: /home/alec/git/hangover/build/libiconv64/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-DPACKAGE_VERSION_STRING=\"1.16\"'
make[2]: *** [Makefile:94: libiconv.res.lo] Error 1
make[2]: Leaving directory '/home/alec/git/hangover/build/libiconv64/lib'
make[1]: *** [Makefile:52: install] Error 2
make[1]: Leaving directory '/home/alec/git/hangover/build/libiconv64'
make: *** [Makefile:86: build/x86_64-w64-mingw32/bin/libcharset-1.dll] Error 2

**Comment by huangguangkan** [comment]
sudo apt-get update
sudo apt-get install mingw-w64

**Comment by alectries** [comment]
mingw-w64 is already installed.

**Comment by AndreRH** [comment]
irrelevant with new Hangover approach
