### ISSUE TITLE
Is a dll, not an executable

### ISSUE THREAD

**Issue by D0gg0Man** [AndreRH/hangover#129]
Heya!

I am trying to get this to work on my Aarch64 Debian however after my succesful build I am getting the following error:

starting L"/root/Downloads/test/notepad++.exe" with Hangover
wine: L"\1f0a\\" is a dll, not an executable

There were no compilation errors and I am getting this with any 64 bit executable. 
a thing to note as well at the "wine: L"\1f0a" part , the string is seemingly random as the next time I ran it I got 4b53 then 167d etc etc. 

## System Details
11gb ram
Qualcomm Aarch64 processor
Distro: Debian XFCE

**Comment by AndreRH** [comment]
Please try again with current master
