### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by handyTheLoser** [AndreRH/hangover#135]
## System Details

What platform are you running on? -->
arm64(l4t)

 Which Hangover version? -->
not sure. i'm guessing 0.8.1

Did you stick to the build instructions from the readme? -->
that's kinda the problem.

## Problems Description
I'm having trouble installing everything. I'm stuck on:
"Place resulting libraries in /opt (default) or set HOLIB to the full path of the resulting library."

I didn't know it the whole build folder is the resulting library or how to copy it to /opt

Reluctantly I skipped that step and was stopped by trying to install llvm-mingw. I get an error when trying to install it saying "E: Unable to locate package llvm-mingw"

I tried installing manually but don't know how to do that neither. I'm but a bit seasoned in ubuntu.

**Comment by AndreRH** [comment]
Hi,
Thanks for the feedback, I'll improve the readme.
In short:

build/libqemu-arm.so or build/libqemu-i386.so are the Qemu libraries depending on what you want to emulate.

for llvm-mingw download and unpack e.g. https://github.com/mstorsjo/llvm-mingw/releases/download/20230320/llvm-mingw-20230320-ucrt-ubuntu-18.04-aarch64.tar.xz
adjust your PATH before configuring wine with:
export PATH=/path/to/llvm-mingw/bin:$PATH

**Comment by AndreRH** [comment]
What error do you get?

**Comment by handyTheLoser** [comment]
I'll have to type it out...

`bison -o tools/widl/parser.tab.c -d ../tools/widl/parser.y ../tools/widl/parser.y:
122.9-25: error: %define variable 'api.location.type' is not used
%define api.location.type {struct location}
Makefile:302389: recipe for target 'tools/widl/parser.tab.h' failed
make: *** [tools/widl/parser.tab.h] Error 1`

**Comment by AndreRH** [comment]
Odd, what does bison --version say?

**Comment by handyTheLoser** [comment]
`bison (GNU Bison) 3.0.4
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is No
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by handyTheLoser** [comment]
I'm working on the Nintendo Switch. It was just an experiment to see how much I can rely on it as a pocket pc. I appreciate your help.
