### ISSUE TITLE
make install fails at dlls/msvcrtd/i386-windows/iob.o

### ISSUE THREAD

**Issue by alectries** [AndreRH/hangover#140]
## System Details

Platform: Debian 11 (kernel 5.10.0-25-arm64)
Hangover: Compiled from git (latest)
Readme compliance: Yes, both with and without optional emulators

## Problems Description

When trying to install a successfully compiled hangover, make install fails at Makefile line 139117 with the following:

```
i686-w64-mingw32-gcc: error: i686-w64-mingw32: No such file or directory
i686-w64-mingw32-gcc: error: unrecognized command-line option ‘-target’
make: *** [Makefile:139117: dlls/msvcrtd/i386-windows/iob.o] Error 1
```

Any advice for getting it past this point? I could always install and ignore errors, but that seems like asking for trouble down the road.

**Comment by AndreRH** [comment]
You could always run it without installing, but was the path to llvm-mingw set?

**Comment by alectries** [comment]
Yes, the path is set. It was required to set the path to compile properly, so that isn’t (shouldn’t be?) the problem.

**Comment by lifning** [comment]
it's likely `sudo` is intentionally ignoring the environment variables of the shell invoking it.
try `sudo env PATH="$PATH" make install` (after adding the llvm-mingw path as before) to work around that restriction

**Comment by AndreRH** [comment]
I was now able to reproduce the problem and indeed the solution provided by @lifning works.
Thanks a lot!
I'll add that to the README.
