### ISSUE TITLE
[Question] When will we see x86_64 support

### ISSUE THREAD

**Issue by 500InternalError** [AndreRH/hangover#142]
It seems that wine developers have implemented initial ARM64EC support, will we see x86_64 support in the near future? What else needs to be done to make that possible?

**Comment by AndreRH** [comment]
I'm currently busy with other areas of Hangover, but as soon as the ARM64EC is usable I'll start looking into plugging in an emulator.

**Comment by 500InternalError** [comment]
Thanks! I'm really looking forward to that.

**Comment by 500InternalError** [comment]
Is there any news about this?

**Comment by AndreRH** [comment]
In Progress, possibly soonish

**Comment by chaitan3** [comment]
Any update on this? There have been a lot of updates on arm64ec in the last few releases, so wonder if it could be attempted soon.

**Comment by AndreRH** [comment]
Well, see the last paragraph of the readme. WineHQ is working on it though, might be ready for wine 10.0 I guess

**Comment by FrostKnight** [comment]
Btw, will it be possible to run any x86 programs like starcraft 2 or starcraft regular on wine? Was curious.

I know it would probably take like RK3588 to run such things though. With even low graphic levels let alone higher.

**Comment by stefand** [comment]
I want to caution against expecting complex online games to work soon. The anti-cheat / DRM systems are tricky enough on x86 and are likely to cause more problems with CPU emulation - although SC2 works inside CrossOver on Apple's Rosetta 2.

On the plus side games have one advantage when it comes to CPU emulation: A lot of the heavy work is done on the system side, inside Vulkan or OpenGL, which doesn't have to run inside the emulator.

We might see a problem similar to 3D driver support in the late 2000s though: The Linux drivers were tested against relatively simple things like Quake 3, Tuxracer and Compiz and trying to run something like Bioshock uncovered a lot of bugs. A similar problem might happen when you confront e.g. the Mali drivers with Diablo 4. The Vulkan testsuite, general progress of Mesa  and modern free software games might make things smoother though.

My testing with hangover v1 was exclusively on Nvidia Tegra, which was running the same Nvidia binary blob that is used on Nvidia desktop GPUs. It had the same pattern of failing/succeeding wine d3d tests.

**Comment by FrostKnight** [comment]
> I want to caution against expecting complex online games to work soon. The anti-cheat / DRM systems are tricky enough on x86 and are likely to cause more problems with CPU emulation - although SC2 works inside CrossOver on Apple's Rosetta 2.
> 
> On the plus side games have one advantage when it comes to CPU emulation: A lot of the heavy work is done on the system side, inside Vulkan or OpenGL, which doesn't have to run inside the emulator.
> 
> We might see a problem similar to 3D driver support in the late 2000s though: The Linux drivers were tested against relatively simple things like Quake 3, Tuxracer and Compiz and trying to run something like Bioshock uncovered a lot of bugs. A similar problem might happen when you confront e.g. the Mali drivers with Diablo 4. The Vulkan testsuite, general progress of Mesa and modern free software games might make things smoother though.
> 
> My testing with hangover v1 was exclusively on Nvidia Tegra, which was running the same Nvidia binary blob that is used on Nvidia desktop GPUs. It had the same pattern of failing/succeeding wine d3d tests.

I figured that Starcraft 2 would have problems on ARM64, even if it was RK3588.  That arm chip is mega powerful but if the compatibility for ARM64 hasn't been ported to a good enough level, it don't matter.

I assume then you guys are less than halfway done in getting anti-cheat games working on ARM64? Let alone SC2 I might add.

Just curious.

**Comment by AndreRH** [comment]
There's a arm64ec branch now, but it's still WIP. I'll try to make a Hangover 9.20 beta with x86-64 support after Wine 9.20 is out

**Comment by AndreRH** [comment]
It's released, spread the word
