### ISSUE TITLE
Not able to set WINEARCH=win32 on latest hangover 9.5

### ISSUE THREAD

**Issue by sammlyu** [AndreRH/hangover#149]
System Details

 What platform are you running on? --> Crostini on ARM Chromebook
 Which Hangover version? --> 9.5
 Did you stick to the build instructions from the readme? --> Install using the deb

 Problems Description

 What emulation dll did you use? --> box64
 What kind of application do you try to run (architecture)? --> i386
 What exactly did you do? --> set WINEARCH=win32 and start winetricks
 Provide a description of the problem here --> I tried to set WINEARCH=win32 to start winetricks but it said it is in WoW64 mode and cannot continue.

**Comment by AndreRH** [comment]
WoW64 only works in a 64-bit wine prefix.

**Comment by sammlyu** [comment]
> WoW64 only works in a 64-bit wine prefix.

Noted. How can I change it to run a 32-bit wine prefix? Originally it uses WINEARCH, but now seems not able to use this.

**Comment by AndreRH** [comment]
Hangover relies on WoW64, so it can't work with a 32-bit prefix. You need to run your i386 application in a 64-bit prefix
