### ISSUE TITLE
Future Request:

### ISSUE THREAD

**Issue by FrostKnight** [AndreRH/hangover#150]
I don't know if you plan to do this or not, but do you already support BSD or just linux?

And also, for those applications that do not need internet, would it be possible to have a flag put in to disable it? 

Thanks in advance.

I have a rockpro64, so I definitely can test.

**Comment by AndreRH** [comment]
Hangover should run on BSD, you might need to through some BSD specific patches on it though. (From your BSD packaging repo).
Your other request is not specific to Hangover, so rather ask that in upstream Wine.

**Comment by FrostKnight** [comment]
Fair point. never mind.
