### ISSUE TITLE
Vulkan not working in Hangover Termux

### ISSUE THREAD

**Issue by Saikatsaha1996** [AndreRH/hangover#151]
## System Details

Android Termux
Hangover 9.7

## Problems Description

Vulkan error 

Added `export BOX64_MMAP32=1`
Then run hangover but same error..
![Screenshot_2024-05-01-22-24-13-16_84d3000e3f4017145260f7618db1d683](https://github.com/AndreRH/hangover/assets/72664192/81ac9cc6-a0bc-45b0-8471-888da7fb4380)

@AndreRH @licy183 can you updated your hangover please? Without those patch we can't use vulkan in hangover for our snapdragon device..

In your box64 haven't this mmap32 features.. & even those wine patches also missing 
## Required for box64
https://github.com/ptitSeb/box64/blob/6d95a644123181addb647f51712ad3e5782d5052/src/core.c#L1043

https://github.com/ptitSeb/box64/blob/6d95a644123181addb647f51712ad3e5782d5052/src/core.c#L60

https://github.com/ptitSeb/box64/blob/main/docs/USAGE.md#box64_mmap32-

## required for wine

[hook_mmap1.diff.txt](https://github.com/termux/termux-packages/files/15242230/hook_mmap1.diff.txt)

[fix-address.diff.txt](https://github.com/termux/termux-packages/files/15242231/fix-address.diff.txt)

And if possible please add support for box64 custom environment variables.. like if we can edit according to our requirements

**Comment by AndreRH** [comment]
Box64 can't use mmap in Hangover as it isn't a win32 API.

**Comment by Saikatsaha1996** [comment]
> Box64 can't use mmap in Hangover as it isn't a win32 API.

Hangover has nice native performance in Termux.. and vulkan problem also solve with new vulkan driver patch (now vulkan support mmap32 features) so now vulkan now working..
![Screenshot_2024-05-11-19-54-36-60_00df01c412509efb9bd6450c382822af](https://github.com/AndreRH/hangover/assets/72664192/62bac893-5285-4da3-bcc7-ee2d84daf954)
![Screenshot_2024-05-11-17-47-37-80_00df01c412509efb9bd6450c382822af](https://github.com/AndreRH/hangover/assets/72664192/97772948-0855-4c27-834a-f6a27c2b2735)


can you add x86-64 application support in hangover?
