### ISSUE TITLE
"termux hangover-wine" program install failed

### ISSUE THREAD

**Issue by hansm629** [AndreRH/hangover#153]
## System Details

- Termux Native XFCE4 desktop environment (host : Galaxy S24+)
- hangover-wine9.7
- Temux tur-multilib package

## Problems Description

- box64cpu.dll
- x86/x64 programs
- Attempt to install program

![Screenshot_2024-05-10_00-43-49](https://github.com/AndreRH/hangover/assets/101167173/074af541-3ce9-40a2-bbba-f799e5bb74b2)

After installing `hangover-wine` through `tur-multilib`

When installing an x86/x64 program, the installation fails with the following error.

Take `notepad++ 64bit` as an example.

```
~ $ wine npp.7.Installer.x64.exe
``` 

If you try to install using the above command, it seems to proceed well as shown below.

![Screenshot_2024-05-10_01-07-46](https://github.com/AndreRH/hangover/assets/101167173/f3850063-ffc5-4602-bde4-9229bff935d7)

but
When you select the [OK] button, the installation window closes and the following error message appears, preventing further progress.

```
~ $ wine npp.7.Installer.x64.exe
00d4:err:nsi:poll_netlink bind failed, errno 13.
0054:err:dnsapi:DllMain No libresolv support, expect problems
0024:err:environ:init_peb starting L"Z:\\data\\data\\com.termux\\files\\home\\Downloads\\npp.7.Installer.x64.exe" in experimental wow64 mode
starting Box64 based box64cpu.dll
0024:err:shell:SHGetFileInfoW pidl is null!
0024:err:wow:BTCpuResetToConsistentState db ExceptionAddress 0000000000000000
``` 

The following is a situation where an attempt to install an x86 program as `wow64` fails.

```
~$ wine Install.exe
00d4:err:nsi:poll_netlink bind failed, errno 13.
0054:err:dnsapi:DllMain No libresolv support, expect problems
0024:err:environ:init_peb starting L"Z:\\storage\\emulated\\0\\Download\\Quick Share\\Hangeul 2010\\Install.exe" in experimental wow64 mode
starting Box64 based box64cpu.dll
0110:err:environ:init_peb starting L"Z:\\storage\\emulated\\0\\Download\\Quick Share\\Hangeul 2010\\install\\setup.exe" in experimental wow64 mode
``` 
```
~$ starting Box64 based box64cpu.dll
Hangover currently has issues with some ACM modules, disabling
0110:fixme:shell:InitNetworkAddressControl stub
0118:err:environ:init_peb starting L"C:\\windows\\syswow64\\msiexec.exe" in experimental wow64 mode
``` 

Is there anything I'm missing?

**※ Both programs had no problem installing on `box64+wine64` in a `proot Debian Linux` environment.**

**Comment by Saikatsaha1996** [comment]
> ## System Details
> * Termux Native XFCE4 desktop environment (host : Galaxy S24+)
> * hangover-wine9.7
> * Temux tur-multilib package
> 
> ## Problems Description
> * box64cpu.dll
> * x86/x64 programs
> * Attempt to install program
> 
> ![Screenshot_2024-05-10_00-43-49](https://private-user-images.githubusercontent.com/101167173/329319112-074af541-3ce9-40a2-bbba-f799e5bb74b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDgyNDAsIm5iZiI6MTcxNTM0Nzk0MCwicGF0aCI6Ii8xMDExNjcxNzMvMzI5MzE5MTEyLTA3NGFmNTQxLTNjZTktNDBhMi1iYmJhLWY3OTllNWJiNzRiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMzMyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjdhNTBiM2VlOWJjOTgxYWE1ZTc4ZDVlMGRmMDVlZTVlMmFiZWYyNjkyNTE3ZDBkMDYyYzEwOGQyYWYyNjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ax6QpCv8kjeyimizzbbemSbFKPjKazsRZI64UbdeUJc)
> 
> After installing `hangover-wine` through `tur-multilib`
> 
> When installing an x86/x64 program, the installation fails with the following error.
> 
> Take `notepad++ 64bit` as an example.
> 
> ```
> ~ $ wine npp.7.Installer.x64.exe
> ```
> 
> If you try to install using the above command, it seems to proceed well as shown below.
> 
> ![Screenshot_2024-05-10_01-07-46](https://private-user-images.githubusercontent.com/101167173/329319213-f3850063-ffc5-4602-bde4-9229bff935d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDgyNDAsIm5iZiI6MTcxNTM0Nzk0MCwicGF0aCI6Ii8xMDExNjcxNzMvMzI5MzE5MjEzLWYzODUwMDYzLWZmYzUtNDYwMi1iZGU0LTkyMjliZmY5MzVkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMzMyMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2M3NjFhNGRhYzdmMzZjZmQyMTAxNmZkNDI1YjFmNWFjOTZlMTkxOTQ0MDVkNTY0NjNhMzQyYTEzM2YxNTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZFuB9kpoO6jetC_gpw66y5UnTbtVcOkBMwjKeQ7zWcU)
> 
> but When you select the [OK] button, the installation window closes and the following error message appears, preventing further progress.
> 
> ```
> ~ $ wine npp.7.Installer.x64.exe
> 00d4:err:nsi:poll_netlink bind failed, errno 13.
> 0054:err:dnsapi:DllMain No libresolv support, expect problems
> 0024:err:environ:init_peb starting L"Z:\\data\\data\\com.termux\\files\\home\\Downloads\\npp.7.Installer.x64.exe" in experimental wow64 mode
> starting Box64 based box64cpu.dll
> 0024:err:shell:SHGetFileInfoW pidl is null!
> 0024:err:wow:BTCpuResetToConsistentState db ExceptionAddress 0000000000000000
> ```
> 
> The following is a situation where an attempt to install an x86 program as `wow64` fails.
> 
> ```
> ~$ wine Install.exe
> 00d4:err:nsi:poll_netlink bind failed, errno 13.
> 0054:err:dnsapi:DllMain No libresolv support, expect problems
> 0024:err:environ:init_peb starting L"Z:\\storage\\emulated\\0\\Download\\Quick Share\\Hangeul 2010\\Install.exe" in experimental wow64 mode
> starting Box64 based box64cpu.dll
> 0110:err:environ:init_peb starting L"Z:\\storage\\emulated\\0\\Download\\Quick Share\\Hangeul 2010\\install\\setup.exe" in experimental wow64 mode
> ```
> 
> ```
> ~$ starting Box64 based box64cpu.dll
> Hangover currently has issues with some ACM modules, disabling
> 0110:fixme:shell:InitNetworkAddressControl stub
> 0118:err:environ:init_peb starting L"C:\\windows\\syswow64\\msiexec.exe" in experimental wow64 mode
> ```
> 
> Is there anything I'm missing?
> 
> **※ Both programs had no problem installing on `box64+wine64` in a `proot Debian Linux` environment.**

64bit application will won't work.. 
Only 32bit app will work

**Comment by hansm629** [comment]
@Saikatsaha1996 
Even when installing a 32-bit program as shown below, the program installation does not proceed.

```
~$ wine Install.exe
00d4:err:nsi:poll_netlink bind failed, errno 13.
0054:err:dnsapi:DllMain No libresolv support, expect problems
0024:err:environ:init_peb starting L"Z:\\storage\\emulated\\0\\Download\\Quick Share\\Hangeul 2010\\Install.exe" in experimental wow64 mode
starting Box64 based box64cpu.dll
0110:err:environ:init_peb starting L"Z:\\storage\\emulated\\0\\Download\\Quick Share\\Hangeul 2010\\install\\setup.exe" in experimental wow64 mode
``` 
```
~$ starting Box64 based box64cpu.dll
Hangover currently has issues with some ACM modules, disabling
0110:fixme:shell:InitNetworkAddressControl stub
0118:err:environ:init_peb starting L"C:\\windows\\syswow64\\msiexec.exe" in experimental wow64 mode
``` 
``` 
wine explorer /desktop=shell explorer
``` 
Enter the above command and
If you run the `Install.exe` in wine explorer, nothing happens.

This program was installed without any problems through `box64+wine64(proot debian)`.

Is there anything that must be installed before installing the program? (ex : .NET Framework)

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 Even when installing a 32-bit program as shown below, the program installation does not proceed.
> 
> ```
> ~$ wine Install.exe
> 00d4:err:nsi:poll_netlink bind failed, errno 13.
> 0054:err:dnsapi:DllMain No libresolv support, expect problems
> 0024:err:environ:init_peb starting L"Z:\\storage\\emulated\\0\\Download\\Quick Share\\Hangeul 2010\\Install.exe" in experimental wow64 mode
> starting Box64 based box64cpu.dll
> 0110:err:environ:init_peb starting L"Z:\\storage\\emulated\\0\\Download\\Quick Share\\Hangeul 2010\\install\\setup.exe" in experimental wow64 mode
> ```
> 
> ```
> ~$ starting Box64 based box64cpu.dll
> Hangover currently has issues with some ACM modules, disabling
> 0110:fixme:shell:InitNetworkAddressControl stub
> 0118:err:environ:init_peb starting L"C:\\windows\\syswow64\\msiexec.exe" in experimental wow64 mode
> ```
> 
> ```
> wine explorer /desktop=shell explorer
> ```
> 
> Enter the above command and If you run the `Install.exe` in wine explorer, nothing happens.
> 
> This program was installed without any problems through `box64+wine64(proot debian)`.
> 
> Is there anything that must be installed before installing the program? (ex : .NET Framework)

Dot net & c++ mandatory

**Comment by hansm629** [comment]
@Saikatsaha1996 
Can you tell me how to install wine mono?

When executing the `box64 winecfg` command in `Proot Debian`,
It was installed automatically

It seems that `hangover-wine` is not installed automatically.

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 Can you tell me how to install wine mono?
> 
> When executing the `box64 winecfg` command in `Proot Debian`, It was installed automatically
> 
> It seems that `hangover-wine` is not installed automatically.

In 

```
wineboot -u
```

**Comment by hansm629** [comment]
@Saikatsaha1996 

Thank you for answer.

When entering the command, an error appears as shown below.
Is it correct that it was processed normally?

```
~$ wineboot -u
020c:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\wineusb.inf"
0228:err:environ:init_peb starting L"C:\\windows\\syswow64\\rundll32.exe" in experimental wow64 mode
starting Box64 based box64cpu.dll
0228:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\kernel32.dll" (error=80)
0228:err:setupapi:create_dest_file failed to create L"C:\\windows\\system32\\kernelbase.dll" (error=80)
Hangover currently has issues with some ACM modules, disabling
0230:err:environ:init_peb starting L"C:\\windows\\syswow64\\iexplore.exe" in experimental wow64 mode
starting Box64 based box64cpu.dll
wine: configuration in L"/data/data/com.termux/files/home/.wine" has been updated.
```

**Comment by hansm629** [comment]
@AndreRH
Could you please help?
I'm wondering if I missed something.

**Comment by AndreRH** [comment]
Try something extremely easy first to see if your setup works. e.g. putty
While I reference the Termux packages, I can't support them, as I'm not actively using them.

Regarding Mono, it can be downloaded from https://dl.winehq.org/wine/wine-mono/ according to the version table in https://wiki.winehq.org/Mono#Versions
and then be installed with `wine msiexec /i /path/to/your/wine-mono-version-x86.msi`

**Comment by hansm629** [comment]
@AndreRH 
```
~$ wine msiexec /i wine-mono-9.1.0-x86.msi
00e0:err:nsi:poll_netlink bind failed, errno 13.
0054:err:dnsapi:DllMain No libresolv support, expect problems
0118:fixme:file:NtLockFile I/O completion on lock not implemented yet
0118:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0118:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0118:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)

``` 

When attempting to install wine-mono manually
It is failing with the above error.

In the case of the above error, is it a problem with `wine9.7` included in `hangover`?
Or is it a problem with `box64?`

**Comment by hansm629** [comment]
@AndreRH 
I've tested it in many ways, but it doesn't seem to be a common symptom.

I will contact `termux tur` for further details.

Thanks for your help :)
