### ISSUE TITLE
Feature request: Fedora package

### ISSUE THREAD

**Issue by m1m1k4tz** [AndreRH/hangover#155]

**Comment by rNoz** [comment]
Yes, please.

**Comment by AndreRH** [comment]
Here is a repo for Fedora:
https://build.opensuse.org/package/show/home:Azkali:Apps/hangover

**Comment by m1m1k4tz** [comment]
> Here is a repo for Fedora: https://build.opensuse.org/package/show/home:Azkali:Apps/hangover

Thanks!
