### ISSUE TITLE
When compiling on fedora I get failed to start wineboot.exe

### ISSUE THREAD

**Issue by m1m1k4tz** [AndreRH/hangover#156]
## System Details

Fedora Asahi Remix

9.9

Yes
## Problems Description

Box64

winecfg 

Follow this guide up until fex emu 
https://gist.github.com/teohhanhui/042a395010d9946ceee14768736e3780
Download llvm mingw 20240518-ucrt-ubuntu-20.04
Then run this script 
https://pastebin.com/raw/hnPQUG8A

Failed to start wineboot.exe 
Failed to load start.exe

**Comment by rNoz** [comment]
In my case, I extracted the ubuntu22 packages (`dpkg-deb -xv $file.deb .`) and then tried to run the local binaries, but it gave the same error.

```shell
$ ./usr/bin/wine winbox.exe
wine: created the configuration directory '/home/xenon/.wine'
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b

$ ./usr/bin/wine winbox64.exe
wine: created the configuration directory '/home/xenon/.wine'
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b

$ ldd usr/bin/wine
        linux-vdso.so.1 (0x0000ffff2348c000)
        libc.so.6 => /lib64/libc.so.6 (0x0000ffff23220000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff23444000)

$ LD_LIBRARY_PATH=$(pwd)/usr/lib ./usr/bin/wine winbox.exe
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b

$ LD_LIBRARY_PATH=$(pwd)/usr/lib ./usr/bin/wine winbox64.exe
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b
```

**Comment by AndreRH** [comment]
You have to build and run it in a 4k container

**Comment by m1m1k4tz** [comment]
I just did that but now I get https://pastebin.com/f87XbqJH

**Comment by AndreRH** [comment]
Why on earth is C:\\windows\\system32\\wineboot.exe a x86-64 file? Did you copy over a wine prefix from somewhere?

**Comment by m1m1k4tz** [comment]
Creating a new wine prefix solved it for me thanks!

**Comment by rNoz** [comment]
> I just did that but now I get https://pastebin.com/f87XbqJG

I am following the instructions you pasted. How do you create a 4k container with distrobox-podman?

**Comment by m1m1k4tz** [comment]
> > I just did that but now I get https://pastebin.com/f87XbqJG
> 
> I am following the instructions you pasted. How do you create a 4k container with distrobox-podman?

Yeah the problem ended up being I was using an old wine prefix from box64

**Comment by rNoz** [comment]
Could you please share the correct one?

I followed all your instructions listed above, and from inside the container (`distrobox enter asahi-krun`), built everything inside and it does trigger the same error:


```
# after make installing it
$ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/lib64/ccache:/home/xenon/.asdf/shims:/home/xenon/.asdf/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/lib/snapd/snap/bin
$ whereis wine
wine: /usr/local/bin/wine /usr/local/lib/wine
$ WINEPREFIX=~/.wine64/ WINEARCH=win64 wine ~/Downloads/winbox64.exe
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b
$ WINEPREFIX=~/.wine/ WINEARCH=win32 wine ~/Downloads/winbox32.exe
wine: WINEARCH is set to 'win32' but this is not supported in wow64 mode.

$ wine anything
wine: failed to start L"C:\\windows\\system32\\wineboot.exe"
0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: failed to load start.exe: c000007b

$ getconf PAGESIZE
16384
```

So, failing for everything. But I don't know how to proceed.

**Comment by m1m1k4tz** [comment]
I remember building it inside the krunvm and I had to hold my MacBook Air up to a fan or it would shut itself off from the heat

**Comment by m1m1k4tz** [comment]
I didn’t make install it either
