### ISSUE TITLE
BOX64_MMAP32 option for box64cpu

### ISSUE THREAD

**Issue by alexvorxx** [AndreRH/hangover#158]
## System Details

 Hangover 9.5

## Problems Description

Hi! 
It is possible to add the **BOX64_MMAP32** option to box64cpu for Wine-Hangover?
This is necessary for Vulkan apps to work on some devices.
https://github.com/ptitSeb/box64/commit/bc852aebeb9852801329f9576b4d5e3fa7df2efa

**Comment by AndreRH** [comment]
See
https://github.com/AndreRH/hangover/issues/151#issuecomment-2106350892

**Comment by alexvorxx** [comment]
> See [#151 (comment)](https://github.com/AndreRH/hangover/issues/151#issuecomment-2106350892)

ok, thanks for the answer
