### ISSUE TITLE
hangover-wine 9.11.1 Box64 doesn't work (endless loop)

### ISSUE THREAD

**Issue by fprietog** [AndreRH/hangover#162]
## System Details

**OS:** Ubuntu 24.04 LTS aarch64
**Host:** Raspberry Pi 4 Model B, 8GB
**Hangover version:** hangover_9.11.1_ubuntu2404_noble_arm64.tar from the Github release.

## Problems Description

**Emulation used:** Box64
**Application to emulate:** The endless loop happens with any use of Box64 emulator.
**Description of the problem:**
Can't start any application with hangover 9.11.1 using Box64 emulator. It causes an endless loop showing these in the command line several times per second:

`00ec:err:wow:BTCpuResetToConsistentState db ExceptionAddress 0000000000000000`
`00ec:err:wow:BTCpuResetToConsistentState db addr 0000000000000000 prot 0`
`00ec:err:wow:BTCpuResetToConsistentState addr prot 0`
`00ec:err:wow:BTCpuResetToConsistentState db_need_test 0`
`00ec:err:wow:BTCpuResetToConsistentState  ctx->Sp       7ffffe1fe340`
`00ec:err:wow:BTCpuResetToConsistentState  ctx->Pc       6ffffd2fc888`

- There isn't additional info in journalctl.
- FEX works, so problem is located only in Box 64. 

Here is a video example of the problem Just installing hangover-wine_9.11.1~noble_arm64.deb and trying to run a Windows x86 application:
https://github.com/user-attachments/assets/bf3c0009-5842-4e2b-86a3-f6d7cffd4c25

If you need more info or tests please don't hesitate to ask. Thank you very much.

**Comment by AndreRH** [comment]
Was a typo, let's make a 9.11.2 :)
