### ISSUE TITLE
run_wineboot failed to start wineboot c000007b on Raspberry Pi 4

### ISSUE THREAD

**Issue by Tianming-Wu** [AndreRH/hangover#164]
## System Details

Raspberry Pi 4 4GB, Ubuntu 24.04.1 LTS, kernel Linux 6.8.0-1010-raspi
hangover_9.15_ubuntu2404_noble_arm64
I didn't build by myself. I used the one in Release.

## Problems Description

I removed the original wine and installed all 3 deb packages in the tar file.

I tried all possibilities, from the box64cpu.dll to other qemu ones.

It is a small game for x86_64 windows, runs normally on my intel pc.
I also tried notepad in ~/.wine/drive_c/windows/ , and the problem remains.

I tried to run it using wine <program.exe>, and it outputs as follows:

0024:err:environ:run_wineboot failed to start wineboot c000007b
wine: could not load kernel32.dll, status c000007b

The same for any applications. For that game, it outputs like this:

0024:err:environ:run_wineboot failed to start wineboot c000007b
0024:err:environ:init_peb starting L"G:\\home\\tianming\\Desktop\\fdir\\chibipire_cn.exe" in experimental wow64 mode
wine: could not load kernel32.dll, status c000007b

I found an issue about Pi 5. Those methods may not work on Pi 4, and because this is the only device available for me currently, I can't take risk to modify my kernel.

Please tell me if there was anything I can do.

**Comment by AndreRH** [comment]
Try a fresh wineprefix like: WINEPREFIX=~/.winehangover wine yourapp.exe

**Comment by AndreRH** [comment]
Or it might be that the larger page size is now also used on Raspi 4?
Check with `getconf PAGESIZE` and report back please

**Comment by Tianming-Wu** [comment]
getconf PAGESIZE returns 4096, I guess 4KB was the intended value.

And prefix WINEPREFIX=~/.winehangover do solves the problem. Thanks.

By the way, I think the app wanted to display Chinese but failed to find usable font files, and ended up displaying boxes. Do you know how to solve that? Copying fonts from windows?

And, I noticed that this action creates a new config directory. Can I delete the old one(~/.wine)?

**Comment by Tianming-Wu** [comment]
getconf PAGESIZE returns 4096, I guess 4KB was the intended value.

And prefix WINEPREFIX=~/.winehangover do solves the problem. Thanks.

By the way, I think the app wanted to display Chinese but failed to find usable font files, and ended up displaying boxes. Do you know how to solve that? Copying fonts from windows?

And, I noticed that this action creates a new config directory. Can I delete the old one(~/.wine)?

**Comment by Tianming-Wu** [comment]
Uh oh, another problem...

```
01b0:err:environ:init_peb starting L"H:\\Dev\\uSyc\\getch.exe" in experimental ARM64EC mode
wine: failed to load /usr/lib/wine/aarch64-windows/ntdll.dll error c00000bb
0024:fixme:shell:IShellBrowser_fnOnViewWindowActive stub, 00007FFFFF18E460 (00007FFFFF1B85D0)
0024:fixme:exec:SHELL_execute flags ignored: 0x0000000c
01b8:err:environ:init_peb starting L"H:\\Dev\\uSyc\\ActivateDetect.exe" in experimental ARM64EC mode
wine: failed to load /usr/lib/wine/aarch64-windows/ntdll.dll error c00000bb
``

That occurs when I'm trying to launch any windowed / cmd based app I made myself using only Win32API (c/c++).
They're compiled using gcc.
I tired launching from bash command line or the wine's explorer, but all failed.
The program is on a removeble disk. But I think that shouldn't be the problem.

Shall I open another issue or do anything else?

**Comment by AndreRH** [comment]
Not sure about the font thing, maybe installing fonts with winetricks helps
You can delete .wine

Your self compiled app seems to be 64-bit which isn't supported yet, try 32-bit
