### ISSUE TITLE
DXVK ARM64EC compilation instructions

### ISSUE THREAD

**Issue by Freak21227** [AndreRH/hangover#167]
## System Details
--> Debian Chroot environment on Poco F5 Pro ,Android 14 with 5.10 kernel 
-->hangover-9.20
-->hangover_9.20_debian12_bookworm_arm64.tar
-4096 pagesize

## Problems Description
i  compiled Arm64ec DXVK binaries according from https://wiki.fex-emu.com/index.php/Development:ARM64EC#dxvk.2Fvkd3d-proton

But i launch x64 a  game i get following errors .

info:info:info:info:info:info:info:
Game:
GTA5.exe
DXVK:v2.4.1-293-g4c0cbbef
Found built-in config:
d3d11.cachedDynamicResources = vi Effective configuration:
d3d11.cachedDynamicResources = vi
Vulkan: Found vkGetInstanceProcAddr in winevulkan.dll @
0x7e5d305bdo
info:
info:info:info:info:info:info:info:info:info:info:info:
Built-in extension providers:
Platform WSI
OpenVR
OpenXR
OpenVR: could not open registry key, status
OpenVR: Failed to locate module
Enabled instance extensions:
VK_EXT_surface_maintenance1
VK_KHR_get_surface_capabilities2
VK _KHR surface
VK_KHR_win32_surface
M_S8_UINT
D3D9: VK_FORMAT _D16_UNORM_S8_UINT -> VK_FORMAT _D24_UNOR
info:
info:info:info:info:info:info:info:info:
Turnip Adreno (TM) 725:
Driver : turnip Mesa driver 24.3
Memory Heap[0]:
Size: 5404 MiB
Flags: 0x1
Memory Type[0]: Property Flags = 0x7 Memory Type[1]: Property Flags = Oxf Memory Type[2]: Property Flags = Oxb
Process set as DPI aware
016c:fixme:dxdiag: vendor_id_to_manufacturer _string Unknown PCI
vendor ID 0x5143.
error: XDG RUNTIME DIR is invalid or not set in the environmen
0148:fixme:d3d:wined3d_guess_card No card selector available t or card vendor 0000 (using GL_RENDERER "zink Vulkan 1.3(Turnip Adreno (TM) 725 (MESA_TURNIP))").
016c:fixme:d3d:wined3d_guess_card No card selector available f or card vendor 0000 (using GL_RENDERER "zink Vulkan 1.3(Turnip Adreno (TM) 725 (MESA_TURNIP))").
0148:fixme:dxgi:dxgi_output_GetDisplayModelist iface 00000077A AF54F90, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0, mode_coun t 00000077AD74F980, modes 0000000000000000 partial stub!
016c:fixme:ddraw:ddraw7_Initialize Ignoring guid {6aea393f-146
1-c20e-e856-8625c9dbe6a1}.
0148:fixme:dxgi:dxgi_output_GetDisplayModeList iface 00000077A AF54F90, format DXGI_FORMAT_R8G8B8A8_UNORM, flags 0, mode_coun t 00000077AD74F980, modes 000000778C903FA0 partial stub!
0148:err:sync:RtlpWaitForCriticalSection section 0000007FFFFCA DB8 "dlls/ntdll/loader.c: loader_section" wait timed out in th read 0148, blocked by 0184, retrying (60 sec)
0184:err:sync:RtlpWaitForCriticalSection section 0000007FFFFCB 3E8 "dlls/ntdll/thread.c: fls_section" wait timed out in threa d 0184, blocked by 0180, retrying (60 sec)
016c:err:sync:RtlpWaitForCriticalSection section 0000007FFFFCA DB8 "dlls/ntdll/loader.c: loader_section" wait timed out in th read 016c, blocked by 0184, retrying (60 sec)

Not:Official dxvk x64 binaries works but graphic performance is low.
Also a suggestion : maybe a dxvk arm64ec debian package alongside with hangover when new  release would be great

**Comment by AndreRH** [comment]
Hi, I plan for a dxvk package, but such issues might be better addressed upstream

**Comment by AndreRH** [comment]
You can find binaries here: https://github.com/AndreRH/hangover/actions/runs/11541634245
Will be part of next release
