### ISSUE TITLE
Problems with mapping memory in 32 bit space

### ISSUE THREAD

**Issue by airidosas252** [AndreRH/hangover#168]
## System Details

Android 14, Samsung Galaxy S23 Ultra, Snapdragon 8 Gen 2, Termux, Termux X11

Hangover-Wine 9.20 compiled for bionic

Box64cpu.dll used for 32 bit x86 emulation

## App/library that is used to reproduce it

A basic Cubemap.exe DirectX demo, that involves DXVK
Any 32 bit application that involves graphics rendering

## Problems Description

So let me reiterate this problem again - by standard a 64 bit Qualcomm Vulkan driver has problems mapping in 32 bit space and it always results in VK_OUT_OF_MEMORY errors. Fortunately there are two solutions:

- Utilizing VK_EXT_map_memory_placed VK extension which the proprietary driver does not support.
- Utilizing MMAP32 hack which is included on box64 by default. 

The latter was used for quite a while with Turnip driver until the driver has included support for that specific VK extension. With proprietary driver however, that is not possible for obvious reasons.

This has been a problem ever since new wow64 mode was introduced and utilized 64 bit libraries for running 32bit x86 apps. Thankfully contributions managed to resolve this completely.

My question - is it possible to implement that so-called "hack"?

**A way to reproduce:** 

- A GPU driver (Turnip for example) that does not have that extension included or utilizing mesa-wrapper which basically wraps the stock Android Vulkan driver for use in X11 environment and Wine as well.
- Utilizing DXVK for wrapping DirectX calls to Vulkan.
- A basic 32 bit DirectX demo (CubeMap.exe) which can showcase that problem.

**What happens when you try running it?**

It results in this:

`info:  DXVK: Read 0 valid state cache entries
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
err:   DxvkMemoryAllocator: Memory allocation failed
err:     Size:      4352`

![Screenshot_20241030_174136_TermuxX11](https://github.com/user-attachments/assets/b6f5ce0c-bcc3-4529-8a74-e4f6a5a3444e)

Mesa-wrapper used to reproduce this:

[https://github.com/xMeM/termux-packages/actions/runs/11580975414](url)

**Comment by AndreRH** [comment]
AFAIK this solved it at least for your usecase: https://github.com/xMeM/termux-packages/commit/2a91f05b6e6cd67aceb515b75e7b5c291cb59e0d

**Comment by airidosas252** [comment]
Yes, consider this issue fixed.
