### ISSUE TITLE
Is it possible to build hangover with winegcc, wineg++, etc.?

### ISSUE THREAD

**Issue by JL2210** [AndreRH/hangover#17]
I have a very limited environment where installing a cross compiler is not practical/possible. Can I use `winegcc` and the other `wine*` tools to build Hangover?

**Comment by JL2210** [comment]
I believe that this is possible now that #13 is merged. I'll try it.

**Comment by stefand** [comment]
Half of hangover is built with winegcc, the other half is built with mingw. Both are necessary, and no, you cannot substitute mingw with winegcc.

The winegcc-built parts run on the host side. They are arm64 ELF binaries. The mingw built parts are guest binaries, x86_64 and i386 PE binaries. They are the guest-side DLL call stubs that the application directly calls into (with an i386 or x86_64 call instruction) and they will call out of the VM into the host parts (with a special syscall instruction). So they need to be built with a compiler that targets the guest side.

You could in theory modify qemu/windows-user/pe.c to load ELF binaries. That way you could build the guest binaries with a Linux compiler, but it still needs to be capable of targeting x86.

The more realistic choice you have is to hack the build process to only build the host parts on your arm machine and compile hangover on a standard Linux or Mac box. Then you can copy the guest side binaries to ARM, they'll will work there as well. Have a look in qemu/x86_64-windows-user/qemu_guest_dll{32/64} after building.

**Comment by JL2210** [comment]
I don't have an ARM machine. I was hoping to run Win32 binaries on x86_64 Chromebooks. Chromebooks have no multilib libraries, so I can't build a WoW64 or pure 32-bit Wine installation.

**Comment by stefand** [comment]
This should conceptionally work. The host Wine is built only for 64 bit, and the hangover thunks take care of thunking. You still need 32 bit guest-side binaries though.

Note though that Hangover itself is highly experimental, so your application is unlikely to work. And I never tested Chromebooks, so this is even less likely to work. Try to run Wine's notepad before you throw anything complicated at it :-)
