### ISSUE TITLE
How to disable WOW64? 

### ISSUE THREAD

**Issue by KimetsuAndrea** [AndreRH/hangover#170]
??(delfin@localhost)-[~]
??? winetricks vcrun2022    
Executing cd /data/data/com.termux/files/usr/bin

warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

warning: You appear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.

Using winetricks 20240105-next - sha256sum: f1ee5af4e2e6daa5d3d72fe7ad2d18d500d311f8e8376f91e65206815e5c2f2e with wine-9.20 (Hangover) and WINEARCH=win64
Executing w_do_call vcrun2022
//////////////////
??(delfin@localhost)-[~]
??? wineboot                                                                1 ?
wine: WINEARCH is set to 'win32' but this is not supported in wow64 mode.

**Comment by KimetsuAndrea** [comment]
┌──(delfin@localhost)-[~]
└─≽ WINEPREFIX="$HOME/prefix32" WINEARCH=win32 wine wineboot
wine: WINEARCH is set to 'win32' but this is not supported in wow64 mode.

**Comment by KimetsuAndrea** [comment]
Please help me bro

**Comment by AndreRH** [comment]
Hangover is based on wow64, you can't disable it. Just make sure WINEARCH is not set to win32.
See also the readme and #149
