### ISSUE TITLE
Can't execute not a single program on android version

### ISSUE THREAD

**Issue by e-cl** [AndreRH/hangover#25]
Hello. My device withour root can't access /data folder, so in winecfg i added disc to accessible sdcard folder. Put some test x86 windows applications. And i can't run any of them. Even simples putty.exe, even notepad++ . They all just give error with just a name of the file, that's all. Could you advise what coul be the problem.

If from command line i cd to directory and type the name of the program, i receive the program is not an internal or external program, nor a batch sxript. Looks like it doesn't locate it, but dir command shows it's there

Sorry, now i see you need to type queme-x86_64.exe.so first. But still nothing runs at all. No errors, nothing

**Comment by stefand** [comment]
There should be a notepad++ embedded in the Android build. Does this run? It is in C:\Program Files, and it should start automatically after your close the initial command prompt

**Comment by e-cl** [comment]
Yes, that one does run. However, the same Notepad++ taken from pc does not. That's strange. Just a single program running? What was the point of releasing this then?

**Comment by stefand** [comment]
I wanted to check if the stuff that we tested runs. I considered it quite possible that e.g. qemu fails to start up due to some differences in Android etc.

I suspect we have a permissions issue when accessing the emulated SD card (and even more so, accessing a real SD card). Android is rather picky there, but I have to defer to André here - I am usually working on desktop Linux systems.

It does run more than Notepad++ of course, but don't expect Hangover to be productively useful. At this point it is at best a techdemo.

**Comment by AndreRH** [comment]
maybe one could pick some commits from here: https://github.com/Eltechs/wine

**Comment by AndreRH** [comment]
or have you tried packing the application as we do it with notepad++ currently?

**Comment by e-cl** [comment]
@AndreRH I'm not sure i understand. How do i pack an application?

**Comment by AndreRH** [comment]
see the end of Makefile.android

**Comment by hacker1024** [comment]
After copying Popcap's Peggle over to "My Documents", I get the same issue.

**Comment by hacker1024** [comment]
(I'm on the latest built release)

**Comment by hacker1024** [comment]
And the same with anything else that I try

**Comment by hacker1024** [comment]
Notepad++ (the preinstalled one) also does this. Could it be related to #58? Specifically, [this comment?](https://github.com/AndreRH/hangover/issues/58#issuecomment-614591176)

The command prompt says the same thing.

**Comment by hacker1024** [comment]
I'm on Android 10

**Comment by AndreRH** [comment]
ARM64 Android is abandoned for now
