### ISSUE TITLE
Required apk file

### ISSUE THREAD

**Issue by foodmaher** [AndreRH/hangover#30]
# What is required of developers ?
- A ready APK is required for Android

# Why do I want it ?
Because I tried a lot to build Hangover using the tools Make or Docker but the two will not work with me I do not know why Is it because of my experience with the Linux system or I use a Linux environment is not integrated or that the process of building Hangover requires access to root powers or because of construction using an Android device.

**WARNING:** You may find it difficult to understand speech because my English is not good.

**Comment by AndreRH** [comment]
It is available under releases for a long time already: https://github.com/AndreRH/hangover/releases

**Comment by foodmaher** [comment]
@AndreRH Thank you for your efforts,
However, there is a problem with your APK upload, which reaches 96%, after which the connection to the server stops and the upload fails.

**Comment by AndreRH** [comment]
closing
