### ISSUE TITLE
black screen with release 0.4 on android

### ISSUE THREAD

**Issue by sazearte** [AndreRH/hangover#31]
Hello i try your release in my android phone (xiaomi mi mix 2 with lineageos 15.1 (android 8.
1))

i install your apk but when i launch application i have this message "setting up the windows environnement"
and after this step i have only black screen

Do you have any idea what caused the error?
is there a way to read the application logs?

**Comment by AndreRH** [comment]
Most likely https://bugs.winehq.org/show_bug.cgi?id=46188
