### ISSUE TITLE
How to compile binary files ?

### ISSUE THREAD

**Issue by foodmaher** [AndreRH/hangover#32]
# The description

When I run a binary application or so called an executable file the error appears incomprehensible and no application works even when I try to run Notepad++. The built - in application also does not work, but it works only once when it closes the first cmd window only ...

# What is required ?

- Why external applications do not work (X86)?
- Are there specific applications running on this application?
- When will the most stable versions of final versions be released?
- Is there a specific way to compile applications or standards?

**NOTE:** These questions were mentioned in my previous issue #30  but no one answered me.

**Comment by sebwie** [comment]
I figured out, that if you close the console window and wait a few seconds, there should start Notepad++! 

If this part works then you can also start your own x86 applications. You can't run x86 directly from the console on ARM-devices, so you have to use the preinstalled and preconfigured qemu-x86 version. 

Alternatively you can go to C:\ and start winestart.cmd which starts a running console in the background and a new empty console. If you close this empty console, then it should also start Notepad++. 

So if these things work, it should be possible running Notepad++ directly from console by the command (but it's very important to type it correct (there is only an error output if you type the first part wrong, the second part goes through all the times):

`c:\x86\qemu-x86_64.exe.so c:\x86\npp\notepad++.exe
`

But at the moment I also couldn't get my own application running. A downloaded Notepad++ in the x86 version didn't start, just loaded a while. 

Later I also wanted to test the x64 version, maybe that's the point.

**Comment by foodmaher** [comment]
@sebwie Thank you.

**Comment by sebwie** [comment]
@foodmaher No problem, I hope it could help you a bit. 

I also tried the x64 version, but this one also didn't work. 
Maybe there are some problems with file permissions, but I don't find out exactly.

**Comment by AndreRH** [comment]
closing then
