### ISSUE TITLE
Building on OSX Mojave

### ISSUE THREAD

**Issue by semaja2** [AndreRH/hangover#35]
Hi,

Can anyone provided guidance on how to compile for OSX Mojave (planning on using in Catalina to run a 32bit exe), I have installed all the depedencies but I am stuck on getting the X libraries

checking for X... no
configure: error: X 64-bit development files not found. Wine will be built
without X support, which probably isn't what you want. You will need
to install 64-bit development packages of Xlib at the very least.
Use the --without-x option if you really want this.

**Comment by stefand** [comment]
Something seems wrong there. I don't think Wine should insist on X11 on Mac because it has winemac.drv, although my own system has the X11 stuff somehow - presumably because I have XQuartz installed.

Either try installing XQuartz or edit the outer makefile to pass --without-x to wine's configure in the build/wine-host/Makefile rule.

**Comment by semaja2** [comment]
Thanks that got it compiling a bit further, however now stuck at the below

`gcc -m64 -c -o svcctl_c.o svcctl_c.c -I. -I../../../../wine/dlls/advapi32 -I../../include \
  -I../../../../wine/include -D__WINESRC__ -D_ADVAPI32_ -D_REENTRANT -fPIC -Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers \
  -Wno-pragma-pack -Wstrict-prototypes -Wtype-limits -Wvla -Wwrite-strings -Wpointer-arith -gdwarf-2 \
  -gstrict-dwarf -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
../../tools/wrc/wrc -o version.res -m64 --nostdinc -I. -I../../../../wine/dlls/advapi32 -I../../include \
  -I../../../../wine/include -D__WINESRC__ -D_ADVAPI32_ ../../../../wine/dlls/advapi32/version.rc
../../tools/winegcc/winegcc -o advapi32.dll.so -B../../tools/winebuild -m64 -fPIC -fasynchronous-unwind-tables \
  -shared ../../../../wine/dlls/advapi32/advapi32.spec advapi.o cred.o crypt.o crypt_arc4.o \
  crypt_des.o crypt_lmhash.o eventlog.o lsa.o registry.o security.o service.o wmi.o svcctl_c.o \
  version.res -lrpcrt4 -lkernelbase ../../libs/port/libwine_port.a -Wb,-drpcrt4 -L/usr/local/opt/bison/lib
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      _CredDeleteW in cred.o
      _mac_enumerate_credentials in cred.o
      _CredReadW in cred.o
      _CredWriteW in cred.o
  "_SecKeychainAddGenericPassword", referenced from:
      _CredWriteW in cred.o
  "_SecKeychainFindGenericPassword", referenced from:
      _CredWriteW in cred.o
  "_SecKeychainGetUserInteractionAllowed", referenced from:
      _mac_enumerate_credentials in cred.o
  "_SecKeychainItemCopyAttributesAndData", referenced from:
      _CredDeleteW in cred.o
      _mac_enumerate_credentials in cred.o
      _CredReadW in cred.o
      _mac_read_credential_from_item in cred.o
  "_SecKeychainItemDelete", referenced from:
      _CredDeleteW in cred.o
  "_SecKeychainItemFreeAttributesAndData", referenced from:
      _CredDeleteW in cred.o
      _mac_enumerate_credentials in cred.o
      _CredReadW in cred.o
      _mac_read_credential_from_item in cred.o
  "_SecKeychainItemModifyAttributesAndData", referenced from:
      _CredWriteW in cred.o
  "_SecKeychainSearchCopyNext", referenced from:
      _CredDeleteW in cred.o
      _mac_enumerate_credentials in cred.o
      _CredReadW in cred.o
  "_SecKeychainSearchCreateFromAttributes", referenced from:
      _CredDeleteW in cred.o
      _mac_enumerate_credentials in cred.o
      _CredReadW in cred.o
  "_SecKeychainSetUserInteractionAllowed", referenced from:
      _mac_enumerate_credentials in cred.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
winegcc: gcc failed
make[2]: *** [advapi32.dll.so] Error 2
make[1]: *** [dlls/advapi32] Error 2
make: *** [build/wine-host/.built] Error 2`

**Comment by stefand** [comment]
I have never seen that issue before. Which Xcode version are you using? Does plain Wine build ok with --enable-win64?

**Comment by semaja2** [comment]
Managed to get it working by removing the "--without-x" and replacing the first line of the Makefile with 

> TESTS := --disable-tests
> #$(if $(NOTESTS),--disable-tests,)

Besides all the other local issues with dependencies etc, and restarting the build from scratch it finally built and I can load the internal apps like "clock.exe" with out issue

However I was aiming to run https://download.mikrotik.com/routeros/winbox/3.19/winbox.exe but get the below 


> Unhandled exception: page fault on read access to 0xf0020790 in 64-bit code (0x00007fff6a1f26f2).
> Register dump:
>  rip:00007fff6a1f26f2 rsp:000000000023e710 rbp:000000000023e710 eflags:00010206 (  R- --  I   - -P- )
>  rax:000000010520b868 rbx:000000000078fd70 rcx:00000000f0020790 rdx:00000000f0020790
>  rsi:0000000000000000 rdi:00000000f0020790  r8:0000000000000000  r9:0000000000000000 r10:00000000000000e4
>  r11:fffffffffffffff0 r12:000000006ab2b000 r13:000000006ab332b0 r14:00000000f0020790 r15:000000000023ee48
> Stack dump:
> 0x000000000023e710:  000000000023e800 00000001006796fc
> 0x000000000023e720:  000000006840cf80 000000006c93ac03
> 0x000000000023e730:  000000006840cf80 000000006c92bd6b
> 0x000000000023e740:  0200000001000000 0800000004000000
> 0x000000000023e750:  2000000010000000 8000000040000000
> 0x000000000023e760:  0000000200000001 0000000800000004
> 0x000000000023e770:  0000002000000010 0000008000000040
> 0x000000000023e780:  0000020000000100 0000080000000400
> 0x000000000023e790:  0000000000000000 0000000000000000
> 0x000000000023e7a0:  0000000000000000 0000000000000000
> 0x000000000023e7b0:  0000000000000000 0000000000000000
> 0x000000000023e7c0:  0000000000000000 0000000000000000
> Backtrace:
> =>0 0x00007fff6a1f26f2 (0x000000000023e710)
> 0x00007fff6a1f26f2: pcmpeqb	(%rdi),%mm0
> Modules:
> Module	Address					Debug info	Name (44 modules)
> PE	        6c810000-        6c99a000	Deferred        winbox
> PE	        71040000-        711f8000	Deferred        kernelbase
> PE	        7b410000-        7b46b000	Deferred        kernel32
> PE	        7bc10000-        7bc14000	Deferred        ntdll
> ELF	        7c400000-        7c404000	Deferred        <wine-loader>
> PE	       100010000-       1000ea000	Deferred        user32
> PE	       1003a0000-       1003a4000	Deferred        gdi32
> PE	       100560000-       100564000	Deferred        advapi32
> PE	       100610000-       100614000	Deferred        msvcrt
> PE	       100cc0000-       100cc4000	Deferred        bcrypt
> PE	       100d00000-       100d04000	Deferred        cabinet
> PE	       100d60000-       100d66000	Deferred        crypt32
> PE	       100ec0000-       100ec4000	Deferred        wined3d
> PE	       101060000-       101064000	Deferred        opengl32
> PE	       101290000-       101294000	Deferred        winemac
> PE	       104e40000-       104e44000	Deferred        ucrtbase
> PE	       104fc0000-       104fc4000	Deferred        dxgi
> PE	       105050000-       105054000	Deferred        iphlpapi
> PE	       1055a0000-       1055a3000	Deferred        kerberos
> PE	       105d70000-       105d73000	Deferred        secur32
> PE	       1079c0000-       1079c4000	Deferred        ws2_32
> PE	       107b10000-       107b13000	Deferred        netapi32
> PE	       107bc0000-       107bc6000	Deferred        windowscodecs
> PE	       107d00000-       107e24000	Deferred        shlwapi
> PE	       107e50000-       107f49000	Deferred        winmm
> PE	       108090000-       108096000	Deferred        winspool
> PE	       108120000-       108147000	Deferred        wsock32
> PE	       108160000-       108185000	Deferred        xinput1_3
> PE	    7ffef0000000-    7ffef001d000	Deferred        version
> PE	    7ffef0130000-    7ffef0179000	Deferred        imm32
> PE	    7ffef0290000-    7ffef02fa000	Deferred        advpack
> PE	    7ffef0300000-    7ffef087a000	Deferred        ole32
> PE	    7ffef0880000-    7ffef0a97000	Deferred        rpcrt4
> PE	    7ffef0aa0000-    7ffef0c3c000	Deferred        setupapi
> PE	    7ffef0c40000-    7ffef0dab000	Deferred        d3d9
> PE	    7ffef0df0000-    7ffef1048000	Deferred        ddraw
> PE	    7ffef1050000-    7ffef11ea000	Deferred        dsound
> PE	    7ffef1320000-    7ffef13a3000	Deferred        mmdevapi
> PE	    7ffef13b0000-    7ffef17a9000	Deferred        oleaut32
> PE	    7ffef17b0000-    7ffef19f1000	Deferred        riched20
> PE	    7ffef1a00000-    7ffef1ada000	Deferred        usp10
> PE	    7ffef1d40000-    7ffef1db6000	Deferred        propsys
> PE	    7ffef1dc0000-    7ffef1e07000	Deferred        shcore
> PE	    7ffef1e10000-    7ffef1e6e000	Deferred        msacm32
> Threads:
> process  tid      prio (all id:s are in hex)
> 00000008 (D) Z:\Users\xxx\Downloads\winbox.exe
> 	00000035    0
> 	00000009    0 <==
> 0000000e services.exe
> 	00000026    0
> 	0000001a    0
> 	00000013    0
> 	00000010    0
> 	0000000f    0
> 00000011 plugplay.exe
> 	00000017    0
> 	00000016    0
> 	00000012    0
> 00000018 winedevice.exe
> 	0000002f    0
> 	0000002e    0
> 	0000002d    0
> 	0000002c    0
> 	0000002b    0
> 	00000029    0
> 	00000025    0
> 	00000024    0
> 	00000023    0
> 	00000020    0
> 	0000001d    0
> 	0000001c    0
> 	0000001b    0
> 	00000019    0
> 0000001e explorer.exe
> 	00000032    0
> 	00000031    0
> 	00000030    0
> 	0000001f    0
> 00000021 winedevice.exe
> 	0000002a    0
> 	00000028    0
> 	00000027    0
> 	00000022    0
> System information:
>     Wine build: wine-1.5.11-42865-gf13edb1f56
>     Platform: x86_64
>     Version: Windows 7
>     Host system: Darwin
>     Host version: 18.7.0

**Comment by stefand** [comment]
The trouble with 32 bit winbox (and I see there is a 64 bit version nowadays) is static msvcrt data. My hack to forward the exports of the host msvcrt broke when I allowed msvcrt to load above 4 GB.

I'm attaching a *very* crude hack that gets it started. I'll clean it up in the next few days, as time permits. Meanwhile, I will close this issue because I think the problem it was about originally is solved.

[winbox.txt](https://github.com/AndreRH/hangover/files/4676883/winbox.txt)
