### ISSUE TITLE
Building on ARM Debian

### ISSUE THREAD

**Issue by thiagoralves** [AndreRH/hangover#36]
I'm trying to build this on a Debian ARM machine (Gemini PDA). I installed all wine dependencies, but make is still failing with a lot of undefined references (xmlNewNs, xmlXpathFreeObject, xmlXPathNodeSetAddUnique, etc...). They seem to be related to libxslt, but I have libxslt1-dev package installed on my system. Any hint?

**Comment by stefand** [comment]
Do you have libxml2:dev?

Also it would be interesting to know at which stage of the hangover build this happens. If it is happening during the build of wine-host then you are missing some Debian packages. If it fails during building of wine-guest or wine-guest32 the Hangover build system screwed up and the Win32/Win64 build of libxml2 or libxslt didn't work right.

**Comment by Dante4** [comment]
After absolutely clean reset (rm -r and git clone) - i got the same error if i do "make". But after i did make -j6 it's worked

**Comment by thiagoralves** [comment]
I followed your advice and ran make -j 6 (Gemini PDA has 10 cores, so I'm
good) after the failed attempt. Unfortunately it failed again, but now with
a different error:

/usr/bin/x86_64-w64-mingw32-windres: dialog control data: not enough binary
data
winebuild: /usr/bin/x86_64-w64-mingw32-windres failed with status 1

Here is a more complete log around the error:

--sysroot=../.. -b x86_64-w64-mingw32 -m64 -fasynchronous-unwind-tables
-shared ../../../../wine/dlls/vcomp120/vcomp120.spec \
  ../../libs/port/libwine_port.a -lwine
../../.././../wine-host/tools/winegcc/winegcc -s -o
user32_test-stripped.exe -B../../.././../wine-host/tools/winebuild \
  --sysroot=../../.. -b x86_64-w64-mingw32 -m64
-fasynchronous-unwind-tables -Wb,-F,user32_test.exe \
  broadcast.o class.o clipboard.o combo.o cursoricon.o dce.o dde.o dialog.o
edit.o generated.o \
  input.o listbox.o menu.o monitor.o msg.o resource.o scroll.o static.o
sysparams.o text.o uitools.o \
  win.o winstation.o wsprintf.o resource.res testlist.o
../../../dlls/user32/libuser32.a \
  ../../../dlls/gdi32/libgdi32.a ../../../dlls/advapi32/libadvapi32.a
/usr/bin/x86_64-w64-mingw32-windres: dialog control data: not enough binary
data
winebuild: /usr/bin/x86_64-w64-mingw32-windres failed with status 1
winegcc: ../../.././../wine-host/tools/winebuild/winebuild failed
Makefile:829: recipe for target 'user32_test-stripped.exe' failed
make[2]: *** [user32_test-stripped.exe] Error 2
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/user32/tests'
Makefile:7507: recipe for target 'dlls/user32/tests' failed
make[1]: *** [dlls/user32/tests] Error 2
make[1]: *** Waiting for unfinished jobs....
../.././../wine-host/tools/widl/widl -o vbscript_classes_r.res -b
x86_64-w64-mingw32 -m64 -I. \
  -I../../../../wine/dlls/vbscript -I../../include
-I../../../../wine/include -D__WINESRC__ \
  ../../../../wine/dlls/vbscript/vbscript_classes.idl
../.././../wine-host/tools/widl/widl -o vbsglobal_t.res -b
x86_64-w64-mingw32 -m64 -I. \
  -I../../../../wine/dlls/vbscript -I../../include
-I../../../../wine/include -D__WINESRC__ \
  ../../../../wine/dlls/vbscript/vbsglobal.idl
../.././../wine-host/tools/widl/widl -o vbsregexp10_t.res -b
x86_64-w64-mingw32 -m64 -I. \
  -I../../../../wine/dlls/vbscript -I../../include
-I../../../../wine/include -D__WINESRC__ \
  ../../../../wine/dlls/vbscript/vbsregexp10.idl
../.././../wine-host/tools/widl/widl -o vbsregexp55_t.res -b
x86_64-w64-mingw32 -m64 -I. \
  -I../../../../wine/dlls/vbscript -I../../include
-I../../../../wine/include -D__WINESRC__ \
  ../../../../wine/dlls/vbscript/vbsregexp55.idl
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/vcomp120'
x86_64-w64-mingw32-gcc -m64 -c -o parser.tab.o parser.tab.c -I.
-I../../../../wine/dlls/vbscript -I../../include \
  -I../../../../wine/include -D__WINESRC__ -D_REENTRANT -Wall -pipe
-fno-strict-aliasing \
  -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers
-Wshift-overflow=2 \
  -Wstrict-prototypes -Wtype-limits -Wunused-but-set-parameter -Wvla
-Wwrite-strings -Wpointer-arith \
  -Wlogical-op -gdwarf-2 -gstrict-dwarf -Wno-format -g -O2 -D_WIN32
x86_64-w64-mingw32-gcc -m64 -c -o compile.o
../../../../wine/dlls/vbscript/compile.c -I.
-I../../../../wine/dlls/vbscript \
  -I../../include -I../../../../wine/include -D__WINESRC__ -D_REENTRANT
-Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body
-Wignored-qualifiers \
  -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits
-Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 -gstrict-dwarf
-Wno-format -g -O2 -D_WIN32
x86_64-w64-mingw32-gcc -m64 -c -o vbregexp.o
../../../../wine/dlls/vbscript/vbregexp.c -I.
-I../../../../wine/dlls/vbscript \
  -I../../include -I../../../../wine/include -D__WINESRC__ -D_REENTRANT
-Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body
-Wignored-qualifiers \
  -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits
-Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 -gstrict-dwarf
-Wno-format -g -O2 -D_WIN32
x86_64-w64-mingw32-gcc -m64 -c -o vbscript_main.o
../../../../wine/dlls/vbscript/vbscript_main.c -I.
-I../../../../wine/dlls/vbscript \
  -I../../include -I../../../../wine/include -D__WINESRC__ -D_REENTRANT
-Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body
-Wignored-qualifiers \
  -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits
-Wunused-but-set-parameter -Wvla \
  -Wwrite-strings -Wpointer-arith -Wlogical-op -gdwarf-2 -gstrict-dwarf
-Wno-format -g -O2 -D_WIN32
../.././../wine-host/tools/winegcc/winegcc -o user32.dll
-B../.././../wine-host/tools/winebuild \
  --sysroot=../.. -b x86_64-w64-mingw32 -m64 -fasynchronous-unwind-tables
-shared ../../../../wine/dlls/user32/user32.spec \
  button.o caret.o class.o clipboard.o combo.o cursoricon.o dde_client.o
dde_misc.o dde_server.o \
  defdlg.o defwnd.o desktop.o dialog.o driver.o edit.o exticon.o focus.o
hook.o icontitle.o input.o \
  listbox.o lstr.o mdi.o menu.o message.o misc.o msgbox.o nonclient.o
painting.o property.o \
  rawinput.o resource.o scroll.o spy.o static.o sysparams.o text.o
uitools.o user_main.o win.o \
  winhelp.o winpos.o winproc.o winstation.o wsprintf.o user32.res
../../dlls/hid/libhid.a \
  ../../dlls/imm32/libimm32.a ../../dlls/setupapi/libsetupapi.a
../../dlls/usp10/libusp10.a \
  ../../dlls/gdi32/libgdi32.a ../../dlls/version/libversion.a
../../dlls/advapi32/libadvapi32.a \
  ../../libs/port/libwine_port.a -lwine
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/user32'
../.././../wine-host/tools/winegcc/winegcc -o vbscript.dll
-B../.././../wine-host/tools/winebuild \
  --sysroot=../.. -b x86_64-w64-mingw32 -m64 -fasynchronous-unwind-tables
-shared ../../../../wine/dlls/vbscript/vbscript.spec \
  compile.o global.o interp.o lex.o regexp.o utils.o vbdisp.o vbregexp.o
vbscript.o vbscript_main.o \
  vbscript.res vbscript_classes_r.res vbsglobal_t.res vbsregexp10_t.res
vbsregexp55_t.res \
  parser.tab.o ../../dlls/oleaut32/liboleaut32.a
../../dlls/ole32/libole32.a \
  ../../dlls/user32/libuser32.a ../../libs/port/libwine_port.a -lwine
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/vbscript'
make[1]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest'
Makefile:102: recipe for target 'wine-guest' failed
make: *** [wine-guest] Error 2

**Comment by Dante4** [comment]
-j6 was example, because my SBC hexcore, but my mad

Well, that's error i have not met, so there i can't help

**Comment by thiagoralves** [comment]
I removed my hangover folder and started over with a new git clone. On my
first make it gave me the libxml errors just like the first time.
Immediately after I ran make again (plain make, no parallel batches with
-j) and I met a different error:

../../dlls/winecrt0/libwinecrt0.a(debug.o): In function
`fallback__wine_dbg_output':
/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/winecrt0/../../../../wine/dlls/winecrt0/debug.c:176:
undefined reference to `__acrt_iob_func'

This is the error I'm getting every time I run make. Below is the complete
log:

make -C build/wine-guest/libs/port
make[1]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/libs/port'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/libs/port'
make -C build/wine-guest
make[1]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/libs/wpp'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/libs/wpp'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/libs/wine'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/libs/wine'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/include'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/include'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/po'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/adsiid'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/adsiid'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dinput'
make[2]: 'libdinput.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dinput'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dinput8'
make[2]: 'libdinput8.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dinput8'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dmoguids'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dmoguids'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dxerr8'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dxerr8'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dxerr9'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dxerr9'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dxguid'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/dxguid'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/mfuuid'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/mfuuid'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr100'
make[2]: 'libmsvcr100.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr100'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr110'
make[2]: 'libmsvcr110.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr110'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr120'
make[2]: 'libmsvcr120.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr120'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr70'
make[2]: 'libmsvcr70.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr70'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr71'
make[2]: 'libmsvcr71.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr71'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr80'
make[2]: 'libmsvcr80.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr80'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr90'
make[2]: 'libmsvcr90.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcr90'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcrt'
make[2]: 'libmsvcrt.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcrt'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcrtd'
make[2]: 'libmsvcrtd.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/msvcrtd'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/strmbase'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/strmbase'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/strmiids'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/strmiids'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/ucrtbase'
make[2]: 'libucrtbase.a' is up to date.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/ucrtbase'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/uuid'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/uuid'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/winecrt0'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/winecrt0'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/wmcodecdspuuid'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/wmcodecdspuuid'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/acledit'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/acledit'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/aclui'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/aclui'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/activeds'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/activeds'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/actxprxy'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/actxprxy'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/adsldp'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/adsldp'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/adsldp/tests'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/adsldp/tests'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/adsldpc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/adsldpc'
make[2]: Entering directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/advapi32'
../.././../wine-host/tools/winegcc/winegcc -o advapi32.dll
-B../.././../wine-host/tools/winebuild \
  --sysroot=../.. -b x86_64-w64-mingw32 -m64 -fasynchronous-unwind-tables
-shared \
  ../../../../wine/dlls/advapi32/advapi32.spec advapi.o cred.o crypt.o
crypt_arc4.o crypt_des.o \
  crypt_lmhash.o eventlog.o lsa.o registry.o security.o service.o wmi.o
svcctl_c.o version.res \
  ../../dlls/rpcrt4/librpcrt4.delay.a ../../dlls/kernelbase/libkernelbase.a
\
  ../../libs/port/libwine_port.a
../../dlls/winecrt0/libwinecrt0.a(debug.o): In function
`fallback__wine_dbg_output':
/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/winecrt0/../../../../wine/dlls/winecrt0/debug.c:176:
undefined reference to `__acrt_iob_func'
../../dlls/winecrt0/libwinecrt0.a(debug.o): In function
`fallback__wine_dbg_header':
/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/winecrt0/../../../../wine/dlls/winecrt0/debug.c:201:
undefined reference to `__acrt_iob_func'
collect2: error: ld returned 1 exit status
winegcc: x86_64-w64-mingw32-gcc failed
Makefile:542: recipe for target 'advapi32.dll' failed
make[2]: *** [advapi32.dll] Error 2
make[2]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest/dlls/advapi32'
Makefile:7712: recipe for target 'dlls/advapi32' failed
make[1]: *** [dlls/advapi32] Error 2
make[1]: Leaving directory
'/home/thiagoralves/Documents/Hangover/hangover/build/wine-guest'
Makefile:102: recipe for target 'wine-guest' failed
make: *** [wine-guest] Error 2

**Comment by stefand** [comment]
The problems that go away with -j 6 (or some other number) are bugs in the Hangover build system. Please send me logs so I can try to find out what's wrong.

__acrt_iob_func, "dialog control data: not enough binary data" are old mingw versions. Sorry, Wine is very picky about having the newest and shiniest since it started migrating many DLLs to mingw builds on a normal x86 / x86_64 build to make copy protection systems happy that compare the file in C:\windows\system32 to the data in memory.

**Comment by Dante4** [comment]
Regarding __acrt_iob_func look there https://github.com/AndreRH/hangover/issues/34

**Comment by thiagoralves** [comment]
I got my mingw from the apt repository. That's probably not the best place
to get the "newest and shiniest". What is a good mingw version that works
to compile wine? I'll try to update mine.

**Comment by Dante4** [comment]
Well it was said that 
> mingw 6.0 here (with gcc 9.2 and binutils 2.32)
Is good version

**Comment by ziqingh** [comment]
The "undefined reference to xml***" error can be fixed by this:

[Link libxml2 for libxslt](https://github.com/ziqingh/hangover/commit/665341fc667ea7474574cd2effa784dd46669360)

**Comment by Trass3r** [comment]
> Well it was said that
> 
> > mingw 6.0 here (with gcc 9.2 and binutils 2.32)
> 
> Is good version

Using latest mingw and ndk leads to `fatal error: 'asm/types.h' file not found` though.

**Comment by AndreRH** [comment]
see #34
and the xml fix was also committed
messing with ndk is not supported here
