### ISSUE TITLE
build error in docker 

### ISSUE THREAD

**Issue by iopass4** [AndreRH/hangover#39]
i am build in docker .run :
docker build -f Dockerfile.android -t hob ./
do it run configure with '--disable-werror '

logs: 

cd build.android/qemu ; PKG_CONFIG_PATH=/root/hangover/build.android/aarch64-linux-android/lib/pkgconfig CC="/root/hangover/build.android/wine-host/tools/winegcc/winegcc -Wno-macro-redefined -D__ANDROID_API__=22 -I/opt/ndk/sysroot/usr/include -L/root/hangover/build.android/aarch64-linux-android/lib --sysroot=/root/hangover/build.android/wine-host -b aarch64-linux-android -B/root/hangover/build.android/wine-host/tools/winebuild -I/root/hangover/build.android/wine-host/include -I/root/hangover/wine/include -DWINE_NOWINSOCK" CXX="" ../../qemu/configure --disable-bzip2 --disable-libusb --disable-sdl --disable-snappy --disable-virtfs --disable-opengl --python=/usr/bin/python2.7 --disable-xen --disable-lzo --disable-qom-cast-debug --disable-vnc --disable-seccomp --disable-strip --disable-hax --disable-gnutls --disable-nettle --disable-replication --disable-tpm --disable-gtk --disable-gcrypt --disable-linux-aio --disable-system --disable-tools --disable-linux-user --disable-guest-agent --enable-windows-user --disable-fdt --disable-capstone ; cd ../.. ; touch build.android/qemu/Makefile

ERROR: configure test passed without -Werror but failed with -Werror.
       This is probably a bug in the configure script. The failing command
       will be at the bottom of config.log.
       You can run configure with --disable-werror to bypass this check.

make -C build.android/qemu
make[1]: Entering directory `/root/hangover/build.android/qemu'
make[1]: *** No targets.  Stop.
make[1]: Leaving directory `/root/hangover/build.android/qemu'
make: *** [build.android/qemu/x86_64-windows-user/qemu-x86_64.exe.so] Error 2
make: Leaving directory `/root/hangover'

**Comment by iopass4** [comment]
run configure with '--disable-werror '

logs:
/opt/ndk/sysroot/usr/include/bits/fortify/string.h:41:1: warning: 'annotate' attribute directive ignored [-Wattributes]
 char* __stpncpy_chk2(char*, const char*, size_t, size_t, size_t) __INTRODUCED_IN(21);
 ^
/opt/ndk/sysroot/usr/include/bits/fortify/string.h:42:1: warning: 'annotate' attribute directive ignored [-Wattributes]
 char* __strncpy_chk2(char*, const char*, size_t, size_t, size_t) __INTRODUCED_IN(21);
 ^
/opt/ndk/sysroot/usr/include/bits/fortify/string.h:47:1: warning: 'annotate' attribute directive ignored [-Wattributes]
 size_t __strlcpy_chk(char*, const char*, size_t, size_t) __INTRODUCED_IN(17);
 ^
/opt/ndk/sysroot/usr/include/bits/fortify/string.h:48:1: warning: 'annotate' attribute directive ignored [-Wattributes]
 size_t __strlcat_chk(char*, const char*, size_t, size_t) __INTRODUCED_IN(17);
 ^
In file included from /root/hangover/qemu/slirp/src/arp_table.c:26:0:
/root/hangover/qemu/slirp/src/slirp.h:19:23: fatal error: sys/timeb.h: No such file or directory
 #include <sys/timeb.h>
                       ^
compilation terminated.
winegcc: aarch64-linux-android-gcc failed
make[2]: *** [/root/hangover/build.android/qemu/slirp/src/arp_table.o] Error 2
make[2]: Leaving directory `/root/hangover/qemu/slirp'
make[1]: *** [slirp/all] Error 2
make[1]: Leaving directory `/root/hangover/build.android/qemu'
make: *** [build.android/qemu/x86_64-windows-user/qemu-x86_64.exe.so] Error 2
make: Leaving directory `/root/hangover'

**Comment by stefand** [comment]
Ow, did I screw up something in recent patches? :-(

**Comment by iopass4** [comment]
I think so.  Just like the error above
