### ISSUE TITLE
./build.android.sh not working with clang

### ISSUE THREAD

**Issue by skompc** [AndreRH/hangover#4]
i fixed this by changing all mention of clang++ to g++ and all mention of clang to gcc
or is there another way around this?
btw im building from cygwin64 on windows

**Comment by skompc** [comment]
just an idea for android support... i made a repo about it
https://github.com/skompc/hold-my-beer
just wondering what you guys think! I'm gonna upload a build once i make it... basically it runs the qemu exe in wine-aarch64 manually

**Comment by AndreRH** [comment]
I laughed quite hard at the name, good choice :D
But I'm not sure how stable this works, because you don't compile qemu with the Android toolchain, do you?
Also cygwin is a bad idea for such a task, also quite slow I bet

**Comment by AndreRH** [comment]
I made some changes, please have a look at the new makefile

**Comment by skompc** [comment]
unrelated bug on github... might make u laugh... btw im cloning repo now, will post results of make
![screenshot](https://user-images.githubusercontent.com/5279725/38959573-c276db74-4326-11e8-8e47-5a56e21089a4.png)

**Comment by skompc** [comment]
didn't work at first but after putting the ndk/bin folder (as well as the ndk/aarch64-linux-andfroid/bin folder) the libpng build worked... freetype compalins:

checking for suffix of native executables... as: unrecognized option '--64'
configure: error: native C compiler is not working

**Comment by skompc** [comment]
ran into some trouble with glib. run the following in glib directory to fix

libtoolize
aclocal
autoconf
autoheader
libtoolize
automake --add-missing


also im stuck in the qemu step... it says zlib check failed

finally which os are you using to build? might help me out
