### ISSUE TITLE
Running failed npp.7.5.4.bin.7z

### ISSUE THREAD

**Issue by iopass4** [AndreRH/hangover#40]
I am trying to run a 32 bit program。such as :(https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.bin.x64.7z) 
It is failed .

**Comment by AndreRH** [comment]
You linked the 64-Bit version

**Comment by iopass4** [comment]
sorry link is https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.bin.7z.a 32 bit program. it is failed /

**Comment by Dante4** [comment]
Try this one
http://download.notepad-plus-plus.org/repository/7.x/7.7.1/npp.7.7.1.bin.minimalist.7z

**Comment by iopass4** [comment]
I want to consult if I don't support 32bit programs.

**Comment by stefand** [comment]
No response in half a year, closing
