### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by seisdr** [AndreRH/hangover#43]
![Screenshot_2019-12-08-23-12-20](https://user-images.githubusercontent.com/45742462/70395501-71d7fa00-1a10-11ea-84b6-69f8959f46d6.png)
This quake2 the one built to Windows RT
Also why is notepad launched auto and how to change the screen size

**Comment by AndreRH** [comment]
To run something built for Windows RT you don't need Hangover, please go to winehq.org
