### ISSUE TITLE
Error with git submodule update

### ISSUE THREAD

**Issue by Dante4** [AndreRH/hangover#45]
error: Server does not allow request for unadvertised object 151e57f0d50649794dfacae32c5641c50211c04b
Fetched in submodule path 'wine', but it did not contain 151e57f0d50649794dfacae32c5641c50211c04b. Direct fetching of that commit failed.

**Comment by stefand** [comment]
Oops, I guess I forgot to push the Wine submodule. The other warning is that the current code is in a rather bad shape - I didn't do any real work on hangover in the past 3 months. I tried to add some of the newer ntdll functionality that kernelbase uses and follow Wine's migration to a PE kernel32 and kernelbase, but I got distracted by non-hangover work halfway through.

**Comment by stefand** [comment]
I forgot to add, I pushed the Wine changes.

If this kind of issue happens again (i.e., I forget to push one of the 3 moduls) check out the following branches: "master" for the top level tree and qemu, "hangover" for Wine. Chances are that things work that way.
