### ISSUE TITLE
Questions about Hangover's design

### ISSUE THREAD

**Issue by mpbagot** [AndreRH/hangover#49]
This isn't so much an issue, as a question about some of the design choices in Hangover. I wasn't sure where else would be suitable.

In the readme, under the 32 bit guest support, three main points are made:

 1) The host Wine is always built as a 64 bit application. Hangover handles 32 bit applications by translating structures passed between the application and Wine.

 2) The address space is limited to 4 GB by reserving every address below 4 GB, then calling mmap to reserve remaining space until we run out of free address space and then freeing up the bottom 4 GB again. Most host Wine libraries are loaded earlier above 4 GB to keep the previous space below 4 GB as free as possible.

 3) Wine sees every process as a 64 bit process, so its WoW64 layer is not active. This will work OK for pure 32 bit or pure 64 bit applications, but it will cause problems for mixed applications that expect a distinction between e.g. C:\windows\system32 and C:\windows\syswow64.

My questions are simply:

1) Why is Wine built as a 64 bit application, rather than using the standard WoW64 + 32 bit build style like most distros provide? Wouldn't this simplify passing structures between the application and Wine? Further, wouldn't is also solve the problem presented in point 3 above? Is there some downside that I'm missing?

2) How does the address spacing actually work? In practice, if a device has less than 4GB of memory, how can host Wine libraries be loaded above that point? Why is this actually done at all?

Apologies if some of these are obvious, I'm just confused, and it is my hope that if I understand why certain things are the way they are, I can solve the issues with the ARM32 port I'm working on.

**Comment by AndreRH** [comment]
1) there are situations like on macos Catalina, where u don't have 32 bits anymore

2) you talk about physical ram, but virtual memory can address more than that

**Comment by mpbagot** [comment]
Thanks for your response, you raise excellent points that I hadn't considered.

One further question I have is in relation to the address space layout. As you mentioned, virtual memory allows for addressing beyond the physical available RAM. However, I still fail to see the purpose for the entire process outlined in point two in the first post.
1) Is there are a specific reason why Wine host libraries should/must be loaded above the 4GB space?
2) As I understand it, this process is not performed by Wine normally, so why does Hangover differ in this regard?

**Comment by stefand** [comment]
> 1. Is there are a specific reason why Wine host libraries should/must be loaded above the 4GB space?

It's not stricly necessary, but it keeps more space free in the lower 4 GB. This space is precious - a bit like the lower 640k during DOS days.

Furthermore we can't prevent this from happening for some libraries, so we might as well make it work for all libraries.

> 2. As I understand it, this process is not performed by Wine normally, so why does Hangover differ in this regard?

Because for Wine the operating system takes care of it when it starts as a 32 bit process. 32 bit processes are naturally limited to 32 bit address space. We are running 32 bit code in a 64 bit process so we have to make sure its resource allocations are addressable ourselves.

**Comment by AndreRH** [comment]
So for an arm32 port you don't have to think about it, just disable the reservation maybe

**Comment by mpbagot** [comment]
Thank you for answering all of my questions.
