### ISSUE TITLE
Best/possible approach to enable network and/or internet

### ISSUE THREAD

**Issue by armwdev** [AndreRH/hangover#51]
What could be the best or possible approaches to enable networking or to access internet using wine on android? Does the hangover has any effects on this matter? 

I am aware that might be better to ask this question in wine forums but I can see it's more active here and hoping to get elaborative response. 

I've tried to ping even it's own ip and loopback address 127.0.0.1 which responds with "Request timed out". 

Is this because some network drivers missing on the guest OS or unimplemented feature by wine or is this some kind of permission issue enforced by the android host? 

Any help or advice would be appreciated.

**Comment by AndreRH** [comment]
Ping is a bad example as it uses icmp which is limited on Android

**Comment by armwdev** [comment]
Thanks a lot for the reply. 

On the wine wiki it says:

> On *NIX systems ICMP ping requires use of raw sockets. To allow Wine opening raw sockets run this command:
`sudo setcap cap_net_raw+epi /usr/bin/wine-preloader `

Is there any possible way to enter this command in a terminal in the Wine Android ecosystem? All we can access is Windows command prompt so not sure how a Linux command can be executed on Android. Instead of pinging, what do you recommend are the possible methods to test if network and internet works?

Thanks again

**Comment by AndreRH** [comment]
That command won't work on Android I guess.
A starting point could putty

**Comment by armwdev** [comment]
I've tried putty inside the wine and also tried termux outside the wine with a rooted android but just no response. 

The weird thing is the internet (iexplore.exe) actually works on x86 android but not on the arm. I think it's more than just a permission or limitation issue because the same limitations should've been also valid for the x86 android as well. 

I am skimming through the source code to see if I can find any pointer about the networking structure between wine and arm android but it seems too complicated.

I would be grateful if you have any pointer on where to look in the source project. Should I just focus on the wineandroid.drv or a different area?

Thanks

**Comment by stefand** [comment]
Wine's iexplore does not work on ARM because there is no ARM build of wine-gecko.

You can try to run the ws2_32 tests (see dlls/ws2_32/tests). You can try the aarch64 ones, and if those work the x86 and x86_64 ones inside hangover. The last time I ran them (years ago) they passed inside hangover, except for one or two I/O completion port tests.

**Comment by armwdev** [comment]
Thanks a lot for the help. I can see the network is actually operational but the methods I've used to test this was just wrong. Now I need to concentrate is how to port a simple D3D9 Win32 SDL application to work in this environment. Should I close this issue and open a new one for that?

**Comment by stefand** [comment]
Yeah, please open new issues for these things.

For d3d9 the wine tests are a good start too. You need desktop GL for Wine, that may be tricky.

Am 10. Jänner 2020 22:06:21 MEZ schrieb armwdev <notifications@github.com>:
>Closed #51.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/AndreRH/hangover/issues/51#event-2939862645

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
