### ISSUE TITLE
Various programs fail to install through Hangover

### ISSUE THREAD

**Issue by mpbagot** [AndreRH/hangover#56]
As mentioned in the README, there are several programs which run correctly through Hangover, but are unable to be installed using their installers, and thus must be copied from an existing Wine installation.

I'd like for this issue to be used by people to track each of the different cases of this occurring, and to help pinpoint the reasons.

At the very least, it would be helpful to provide screenshots of where certain installers fail, versus the expected successful output on a standard Wine install. Also of use would be debug logs from Wine, with warn, error and fixme output enabled at least.

**Comment by mpbagot** [comment]
The first program I have noticed this issue occurring with, is Steam. On a WoW64 install of Wine 3.0 on an x86_64 PC, Steam installs as expected and can be launched. However, when running the same installer through a build of Hangover's current master branch, the installer hangs after creating the shortcut in C:\ProgramData. I left it for about 15 minutes, during which it made no visible progress.

Screenshot of the Steam installer under WoW64 Wine 3.0:
![Steam install x86 wine](https://user-images.githubusercontent.com/17587250/73037847-91ce5a80-3ea4-11ea-9441-88e435d0108e.png)

Screenshot of where Steam installer hangs under Hangover:
![Steam install arm64 hangover](https://user-images.githubusercontent.com/17587250/73038772-c263c380-3ea7-11ea-9f39-9ffbf68ccbf4.png)

**Comment by stefand** [comment]
I would be very surprised if Steam runs in hangover, yet alone its copy protection system and games :-)

**Comment by AndreRH** [comment]
Please retest in a modern version of Hangover
