### ISSUE TITLE
Applications are not displayed on Android

### ISSUE THREAD

**Issue by AndreRH** [AndreRH/hangover#58]
We finally have CI for building, yay!
But sadly notepad++ isn't popping up on my phone while wineconsole and other built-in apps work. That's with the current build. Hangover 0.4 works.
I did some initial debugging, and it seems they are running, but are not visible. First guess would be the user32 wrapper, but it needs more debugging...

**Comment by cam1965** [comment]
Mine running from c:\x86\npp\notepad++.exe shows : Can't recognize notepad++.exe as an internal or external command or batch script. Also other apps like clock , wineconsole, notepad.exe are working.

**Comment by hacker1024** [comment]
@cam1965 What Android version do you have?

**Comment by hacker1024** [comment]
https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission

**Comment by hacker1024** [comment]
I suspect no x86/x64 apps will run on Android 10+ because QEMU is located in the app's data directory.

Native binaries are fine because `wine` is inside the apk itsef.

**Comment by cam1965** [comment]
> @cam1965 What Android OS version do you have?

Android 9

**Comment by easyaspi314** [comment]
Termux has run into a similar situation, discussed at length here. 

https://github.com/termux/termux-app/issues/1072

**Comment by AndreRH** [comment]
ARM64 Android is abandoned for now, please use https://github.com/AndreRH/hangover/releases/tag/hangover-0.4.0
