### ISSUE TITLE
Compile qemu dll error ( msvcrt.dll ) 

### ISSUE THREAD

**Issue by cam1965** [AndreRH/hangover#61]
Just started  to compile  qemu  ( since already compiled wine ).
The first 2 dlls compiled fine ( kernel32.dll and ntdll.dll )  . The 3rd (  msvcrt.dll ) didn't . 
The error is below. Please help me. Thanks.

i686-w64-mingw32-gcc ../../../dlls/msvcrt/undname.c -c -o undname_g.o -I../../../dlls/msvcrt/../include -I../../../dlls/msvcrt/../../qemu/include -DQEMU_CURRENT_DLL=DLL_MSVCRT -O2 -DGUEST_BIT=32 -DHOST_BIT=64 -D_MSVCR_VER=0 -D_WIN32_WINNT=0x0603 -DQEMU_DLL_GUEST
i686-w64-mingw32-gcc ../../../dlls/msvcrt/wcs.c -c -o wcs_g.o -I../../../dlls/msvcrt/../include -I../../../dlls/msvcrt/../../qemu/include -DQEMU_CURRENT_DLL=DLL_MSVCRT -O2 -DGUEST_BIT=32 -DHOST_BIT=64 -D_MSVCR_VER=0 -D_WIN32_WINNT=0x0603 -DQEMU_DLL_GUEST
../../../build/wine-host/tools/winegcc/winegcc -B ../../../build/wine-host/tools/winebuild/winebuild -I../../../build/wine-host/include -I../../../wine/include  -shared -b i686-w64-mingw32 ../../../dlls/msvcrt/msvcrt.spec -L/home/gemini/hangover/build/wine-guest32/dlls  *_g.o ../../wine-guest32/dlls/winecrt0/libwinecrt0.a -o msvcrt.dll -lkernel32 -l ntdll -nodefaultlibs -nostdlib -Wl,--image-base,0x30000000 -lntdll
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_ctor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_ctor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_copy_ctor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_ctor_charptr: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_exception_ctor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_exception_ctor_noalloc: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_exception_copy_ctor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_exception_default_ctor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_dtor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_exception_dtor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_type_info_dtor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_opequals: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_type_info_opequals_equals: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_type_info_opnot_equals: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_vector_dtor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_exception_vector_dtor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_default_ctor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_bad_cast_scalar_dtor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_exception_scalar_dtor: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_type_info_before: symbol not defined
/usr/bin/i686-w64-mingw32-ld: cannot export __thiscall___thiscall_MSVCRT_what_exception: symbol not defined
/usr/bin/i686-w64-mingw32-ld: warning: cannot find entry symbol _DllMainCRTStartup@12; defaulting to 0000000030001000
/usr/bin/i686-w64-mingw32-ld: except_g.o:except.c:(.text+0x621): undefined reference to `strcmp'
/usr/bin/i686-w64-mingw32-ld: except_g.o:except.c:(.text+0x944): undefined reference to `memmove'
/usr/bin/i686-w64-mingw32-ld: except_g.o:except.c:(.text+0x9a0): undefined reference to `memmove'
collect2: error: ld returned 1 exit status
winegcc: i686-w64-mingw32-gcc failed
make[1]: *** [../../../dlls/msvcrt/Makefile:12: msvcrt.dll] Error 2
make[1]: Leaving directory '/home/gemini/hangover/build/dlls32/msvcrt'
make: *** [Makefile:199: build/dlls32/msvcrt/msvcrt.dll] Error 2
gemini@cosmopda:~/hangover$

**Comment by AndreRH** [comment]
Closing due to broken setup
