### ISSUE TITLE
git submodule update stops and do nothing 

### ISSUE THREAD

**Issue by cam1965** [AndreRH/hangover#62]
You have closed my previous posts. My setup is Ok. Only I have updated manually . Please seee again my answers in the closed posts. I have compared all the files from  my hangover tree and it was the same as the files in your site. I have compared every file and it is the same. only I have changed Makefile, because the optiions in winecfg is updated and for example --winebuild was now -B. You can check this. Also you can check that when you download hangover with git and do a git submodule update it stops and do nothing . Please you can check this.

emini@cosmopda:~/Downloads/hangover$ git init update
Initialized empty Git repository in /home/gemini/Downloads/hangover/update/.git/
gemini@cosmopda:~/Downloads/hangover$ git submodule init
Submodule 'freetype' (https://github.com/aseprite/freetype2) registered for path 'freetype'
Submodule 'glib' (https://github.com/AndreRH/glib.git) registered for path 'glib'
Submodule 'libpng' (https://github.com/glennrp/libpng) registered for path 'libpng'
Submodule 'libxml2' (https://gitlab.gnome.org/GNOME/libxml2.git) registered for path 'libxml2'
Submodule 'libxslt' (https://gitlab.gnome.org/GNOME/libxslt.git) registered for path 'libxslt'
Submodule 'qemu' (https://github.com/AndreRH/qemu.git) registered for path 'qemu'
Submodule 'wine' (https://github.com/AndreRH/wine.git) registered for path 'wine'
gemini@cosmopda:~/Downloads/hangover$ git submodule update
Cloning into '/home/gemini/Downloads/hangover/freetype'...
It tries to clone freetype, but it stops as above and do nothing.
only if I did a  git clone https://github.com/aseprite/freetype2 manually the submodule is updated.
Thank you.

**Comment by cam1965** [comment]
Please reopen my case of qemu error compiling the dll. Thanks.

**Comment by AndreRH** [comment]
As I told you it works, just not in your case.
And manually download is not enough, you also have to checkout the correct branch and/or version.

**Comment by cam1965** [comment]
ok. But you can check that the wine after is compiled does not support --winebuild and wine-objdir . Now it works with -B and sysroot. So , I had to change this in Makefile. Thanks.
see below
gemini@cosmopda:~/hangover/build/wine-host/tools/winegcc$ ./winegcc --help|more
Usage: gcc [options] file...
Options:
  -pass-exit-codes         Exit with highest error code from a phase.
  --help                   Display this information.
  --target-help            Display target specific command line options.
  --help={common|optimizers|params|target|warnings|[^]{joined|separate|undocumented}}[,...].
                           Display specific types of command line options.
  (Use '-v --help' to display command line options of sub-processes).
  --version                Display compiler version information.
  -dumpspecs               Display all of the built in spec strings.
  -dumpversion             Display the version of the compiler.
  -dumpmachine             Display the compiler's target processor.
  -print-search-dirs       Display the directories in the compiler's search path.
  -print-libgcc-file-name  Display the name of the compiler's companion library.
  -print-file-name=<lib>   Display the full path to library <lib>.
  -print-prog-name=<prog>  Display the full path to compiler component <prog>.
  -print-multiarch         Display the target's normalized GNU triplet, used as
                           a component in the library path.
  -print-multi-directory   Display the root directory for versions of libgcc.
  -print-multi-lib         Display the mapping between command line options and
                           multiple library search directories.
  -print-multi-os-directory Display the relative path to OS libraries.
  -print-sysroot           Display the target libraries directory.
  -print-sysroot-headers-suffix Display the sysroot suffix used to find headers.
  -Wa,<options>            Pass comma-separated <options> on to the assembler.
  -Wp,<options>            Pass comma-separated <options> on to the preprocessor.
  -Wl,<options>            Pass comma-separated <options> on to the linker.
  -Xassembler <arg>        Pass <arg> on to the assembler.
--More--
gemini@cosmopda:~/hangover/build/wine-host/tools/winegcc$ ./winegcc --help|more
Usage: gcc [options] file...
Options:
  -pass-exit-codes         Exit with highest error code from a phase.
  --help                   Display this information.
  --target-help            Display target specific command line options.
  --help={common|optimizers|params|target|warnings|[^]{joined|separate|undocumented}}[,...].
                           Display specific types of command line options.
  (Use '-v --help' to display command line options of sub-processes).
  --version                Display compiler version information.
  -dumpspecs               Display all of the built in spec strings.
  -dumpversion             Display the version of the compiler.
  -dumpmachine             Display the compiler's target processor.
  -print-search-dirs       Display the directories in the compiler's search path.
  -print-libgcc-file-name  Display the name of the compiler's companion library.
  -print-file-name=<lib>   Display the full path to library <lib>.
  -print-prog-name=<prog>  Display the full path to compiler component <prog>.
  -print-multiarch         Display the target's normalized GNU triplet, used as
                           a component in the library path.
  -print-multi-directory   Display the root directory for versions of libgcc.
  -print-multi-lib         Display the mapping between command line options and
                           multiple library search directories.
  -print-multi-os-directory Display the relative path to OS libraries.
  -print-sysroot           Display the target libraries directory.
  -print-sysroot-headers-suffix Display the sysroot suffix used to find headers.
  -Wa,<options>            Pass comma-separated <options> on to the assembler.
  -Wp,<options>            Pass comma-separated <options> on to the preprocessor.
  -Wl,<options>            Pass comma-separated <options> on to the linker.
  -Xassembler <arg>        Pass <arg> on to the assembler.
--More--
-Xpreprocessor <arg>     Pass <arg> on to the preprocessor.
  -Xlinker <arg>           Pass <arg> on to the linker.
  -save-temps              Do not delete intermediate files.
  -save-temps=<arg>        Do not delete intermediate files.
  -no-canonical-prefixes   Do not canonicalize paths when building relative
                           prefixes to other gcc components.
  -pipe                    Use pipes rather than intermediate files.
  -time                    Time the execution of each subprocess.
  -specs=<file>            Override built-in specs with the contents of <file>.
  -std=<standard>          Assume that the input sources are for <standard>.
  --sysroot=<directory>    Use <directory> as the root directory for headers
                           and libraries.
  -B <directory>           Add <directory> to the compiler's search paths.
  -v                       Display the programs invoked by the compiler.
  -###                     Like -v but options quoted and commands not executed.
  -E                       Preprocess only; do not compile, assemble or link.
  -S                       Compile only; do not assemble or link.
  -c                       Compile and assemble, but do not link.
  -o <file>                Place the output into <file>.
  -pie                     Create a dynamically linked position independent
                           executable.
  -shared                  Create a shared library.
  -x <language>            Specify the language of the following input files.
                           Permissible languages include: c c++ assembler none
                           'none' means revert to the default behavior of
                           guessing the language based on the file's extension.

Options starting with -g, -f, -m, -O, -W, or --param are automatically

**Comment by cam1965** [comment]
also git submodule update is not working.  Please check this 
Thank you.

**Comment by cam1965** [comment]
I will try to do git submodule update and wait a lot more . I will wait for 2 hours and see what will hapen. thank you. after this,  if it works ,I will try to compile again.

**Comment by AndreRH** [comment]
You are using the wrong wine version and thus needed the wrong makefile changes.
For the git submodule problem ask for help at git

**Comment by cam1965** [comment]
Hi, after waiting a long time , the git submodule update ends with successs. Compiled with  successfull. But when running a program an error appears as below
gemini@cosmopda:~$ hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe /home/gemini/Downloads/notepad/notepad++.exe 
wine: cannot find 'C:\x86\qemu-x86_64.exe.so'
gemini@cosmopda:~$ 
Please help me. I will close this posts and open another. Thank you again
