### ISSUE TITLE
Library zlib1.dll (which is needed by L"C:\\windows\\system32\\dbghelp.dll") not found

### ISSUE THREAD

**Issue by cam1965** [AndreRH/hangover#64]
Hi. After a successful git submodule update , I have compiled hangover like a charm without any modifications. But when I have tried to execute it an error has appeared  as below.
Please help me . Thank you

gemini@cosmopda:~$ hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/Downloads/notepad/notepad++.exe 
32 bit environment set up, Large Address Aware: NO.
0009:err:qemu_module:import_dll Library zlib1.dll (which is needed by L"C:\\windows\\system32\\dbghelp.dll") not found
0009:err:qemu_module:import_dll Library dbghelp.dll (which is needed by L"G:\\home\\gemini\\Downloads\\notepad\\notepad++.exe") not found
0009:err:qemu_module:qemu_LdrInitializeThunk Main exe initialization for L"G:\\home\\gemini\\Downloads\\notepad\\notepad++.exe" failed, status c0000135
Process initialization failed.

**Comment by cam1965** [comment]
But these files are in my system as below
gemini@cosmopda:~$ sudo find / -name zlib1.dll
find: ‘/proc/32622’: No such file or directory
/usr/i686-w64-mingw32/lib/zlib1.dll
/usr/x86_64-w64-mingw32/lib/zlib1.dll
gemini@cosmopda:~$ sudo find / -name dbghelp.dll
find: ‘/proc/32744’: No such file or directory
/home/gemini/.wine/drive_c/windows/system32/dbghelp.dll
/home/gemini/hangover-git/build/wine-guest/dlls/dbghelp/dbghelp.dll
/home/gemini/hangover-git/build/wine-guest32/dlls/dbghelp/dbghelp.dll
/home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu_guest_dll32/dbghelp.dll
/home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu_guest_dll64/dbghelp.dll
/usr/lib/aarch64-linux-gnu/wine-development/fakedlls/dbghelp.dll
/usr/lib/aarch64-linux-gnu/wine/fakedlls/dbghelp.dll
gemini@cosmopda:~$

**Comment by cam1965** [comment]
also tried  :
gemini@cosmopda:~$ hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/.wine/drive_c/windows/notepad.exe 
Failed to load "/home/gemini/.wine/drive_c/windows/notepad.exe", last error 126.

**Comment by cam1965** [comment]
also 
gemini@cosmopda:~/hangover-git/build/wine-guest32/programs/notepad$ cd
gemini@cosmopda:~$ hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/hangover-git/build/wine-guest32/programs/notepad/
Failed to load "/home/gemini/hangover-git/build/wine-guest32/programs/notepad/", last error 126.
gemini@cosmopda:~$

**Comment by cam1965** [comment]
this works great 

hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/hangover-git/build/wine-guest/programs/notepad/notepad.exe 
so I think the proble is 32 bit program , right ?

**Comment by cam1965** [comment]
but wordpad 32 works
hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/hangover-git/build/wine-guest32/programs/wordpad/wordpad.exe

**Comment by cam1965** [comment]
this works 
hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/hangover-git/build/wine-guest32/programs/notepad/notepad.exe

**Comment by cam1965** [comment]
this didnt work
hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/hangover-git/build/wine-guest32/programs/iexplore/iexplore.exe 
32 bit environment set up, Large Address Aware: YES.
0009:err:qemu_module:import_dll Library zlib1.dll (which is needed by L"C:\\windows\\system32\\wininet.dll") not found
0009:err:qemu_module:import_dll Library wininet.dll (which is needed by L"C:\\windows\\system32\\urlmon.dll") not found
0009:err:qemu_module:import_dll Library urlmon.dll (which is needed by L"C:\\windows\\system32\\ieframe.dll") not found
0009:err:qemu_module:import_dll Library ieframe.dll (which is needed by L"G:\\home\\gemini\\hangover-git\\build\\wine-guest32\\programs\\iexplore\\iexplore.exe") not found
0009:err:qemu_module:qemu_LdrInitializeThunk Main exe initialization for L"G:\\home\\gemini\\hangover-git\\build\\wine-guest32\\programs\\iexplore\\iexplore.exe" failed, status c0000135
Process initialization failed.

**Comment by cam1965** [comment]
this also didnt work
hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/hangover-git/build/wine-guest/programs/iexplore/iexplore.exe 
0009:fixme:qemu_module:import_dll No implementation for ntdll.dll.NtSetContextThread imported from L"C:\\windows\\system32\\kernelbase.dll", setting to 0x752cceab00
0009:err:qemu_module:import_dll Library zlib1.dll (which is needed by L"C:\\windows\\system32\\wininet.dll") not found
0009:err:qemu_module:import_dll Library wininet.dll (which is needed by L"C:\\windows\\system32\\urlmon.dll") not found
0009:err:qemu_module:import_dll Library urlmon.dll (which is needed by L"C:\\windows\\system32\\ieframe.dll") not found
0009:err:qemu_module:import_dll Library ieframe.dll (which is needed by L"G:\\home\\gemini\\hangover-git\\build\\wine-guest\\programs\\iexplore\\iexplore.exe") not found
0009:err:qemu_module:qemu_LdrInitializeThunk Main exe initialization for L"G:\\home\\gemini\\hangover-git\\build\\wine-guest\\programs\\iexplore\\iexplore.exe" failed, status c0000135
Process initialization failed.

**Comment by AndreRH** [comment]
try:
cp /usr/i686-w64-mingw32/lib/zlib1.dll build/qemu/x86_64-windows-user/qemu_guest_dll32
cp /usr/x86_64-w64-mingw32/lib/zlib1.dll build/qemu/x86_64-windows-user/qemu_guest_dll64

**Comment by cam1965** [comment]
hi. thank you.
didnt work for notepad++ 64 bit and 32 bit. please seee below. But I have downloaded an older version of notepad++ and it worked. 

gemini@cosmopda:~$ hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/Downloads/npp/notepad++.exe 
0031:fixme:qemu_module:import_dll No implementation for ntdll.dll.NtSetContextThread imported from L"C:\\windows\\system32\\kernelbase.dll", setting to 0x7a975e3b00
0031:fixme:qemu_module:import_dll No implementation for msvcrt.dll._wopen imported from L"G:\\home\\gemini\\hangover-git\\build\\qemu\\x86_64-windows-user\\qemu_guest_dll64\\zlib1.dll", setting to 0x7a975e3b00
0031:fixme:qemu_ntdll:qemu_LdrDisableThreadCalloutsForDll Unverified!
0031:fixme:qemu_ntdll:qemu_RtlUnicodeStringToAnsiString Unverified!
0031:fixme:qemu_ntdll:qemu_LdrGetProcedureAddress Unverified!
0031:fixme:qemu_ntdll:qemu_LdrGetProcedureAddress Unverified!
0031:fixme:qemu_ntdll:qemu_LdrDisableThreadCalloutsForDll Unverified!
0031:fixme:qemu_ntdll:qemu_strncmp Unverified!
0031:fixme:qemu_ntdll:qemu_strncmp Unverified!
0031:fixme:qemu_ntdll:qemu_strncmp Unverified!
0031:fixme:qemu_ntdll:qemu_strncmp Unverified!
0031:fixme:qemu_ntdll:qemu_strncmp Unverified!
----------------------------------------------
hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/Downloads/npp32/notepad++.exe
32 bit environment set up, Large Address Aware: NO.
0034:fixme:qemu_module:import_dll No implementation for msvcrt.dll._wopen imported from L"G:\\home\\gemini\\hangover-git\\build\\qemu\\x86_64-windows-user\\qemu_guest_dll32\\zlib1.dll", setting to 0x763f1e6b00
0034:err:qemu_msvcrt:qemu_init_dll loaded 0x763dbb0000
0034:fixme:qemu_ntdll:qemu_LdrDisableThreadCalloutsForDll Unverified!
0034:fixme:qemu_ntdll:qemu_RtlUnicodeStringToAnsiString Unverified!
0034:fixme:qemu_ntdll:qemu_LdrGetProcedureAddress Unverified!
0034:fixme:qemu_ntdll:qemu_LdrGetProcedureAddress Unverified!
0034:fixme:qemu_ntdll:qemu_LdrDisableThreadCalloutsForDll Unverified!
0034:fixme:qemu_module:qemu_LoadLibrary unsupported flag(s) used

-------------------------------------------------------

this below old versio worked 

gemini@cosmopda:~$ hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/Downloads/notepad++/notepad++.exe 
32 bit environment set up, Large Address Aware: NO.
0009:err:qemu_msvcrt:qemu_init_dll loaded 0x7ee5390000
0009:fixme:qemu_ntdll:qemu_LdrDisableThreadCalloutsForDll Unverified!
0009:fixme:qemu_ntdll:qemu_RtlUnicodeStringToAnsiString Unverified!
0009:fixme:qemu_ntdll:qemu_LdrGetProcedureAddress Unverified!

**Comment by stefand** [comment]
I am surprised that our guest dbghelp even builds with zlib enabled. I guess you have a mingw that ships with zlib headeres and libs whereas mine does not.

That said, the problem with the new notepad++ version should be fixable by implementing _wopen in our thunk msvcrt.

**Comment by cam1965** [comment]
Ok. Thank you again for the explanation.

**Comment by stefand** [comment]
32 bit notepad++ version 7.8.6 works for me, but my 32 bit windows PE build environment does not have zlib, so my dbghelp.dll is built without it. Meanwhile my recent Wine rebasing work might changer a few things, especially re ucrtbase.dll. Can you retry with current git?

**Comment by cam1965** [comment]
After 9 hours  of compiling: 
Didn't work. And also the old version that was working in the past , now doesn't work. I will not compile again. Much  work. Sorry.
below  the error :
gemini@cosmopda:~/hangover-git/build/wine-host$ WINEPREFIX=/home/gemini/.wine64 ./wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/Downloads/npp7.8.6/notepad++.exe 
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
32 bit environment set up, Large Address Aware: NO.
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\WINTRUST.dll", setting to 0x7e921099a0
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_sprintf Calling host msvcrt instead of ntdll for now.
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\uxtheme.dll", setting to 0x7e921099a0
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
Segmentation fault

**Comment by cam1965** [comment]
also with old  version of notepad ( old version )  that was working in the past 

emini@cosmopda:~/hangover-git/build/wine-host$ WINEPREFIX=/home/gemini/.wine64 ./wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/Downloads/notepad++/notepad++.exe 
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
32 bit environment set up, Large Address Aware: NO.
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_sprintf Calling host msvcrt instead of ntdll for now.
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\uxtheme.dll", setting to 0x7161d569a0
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vfprintf imported from L"C:\\windows\\system32\\OLEAUT32.dll", setting to 0x7161d569a0
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\OLEAUT32.dll", setting to 0x7161d569a0
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_kernel32:qemu_Wow64DisableWow64FsRedirection Unverified!
0009:fixme:qemu_kernel32:qemu_Wow64RevertWow64FsRedirection Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:ver:GetCurrentPackageId (0x6c97c4 (nil)): stub
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Segmentation fault

**Comment by cam1965** [comment]
also notepad 64 bit didn't work 
gemini@cosmopda:~/hangover-git/build/wine-host$ WINEPREFIX=/home/gemini/.wine64 ./wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/Downloads/npp7.8.6-64bit/notepad++.exe 
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\WINTRUST.dll", setting to 0x727a5a19a0
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_sprintf Calling host msvcrt instead of ntdll for now.
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\uxtheme.dll", setting to 0x727a5a19a0
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
Segmentation fault

**Comment by cam1965** [comment]
also error with notepad compiled inside hangover :
gemini@cosmopda:~/hangover-git/build/wine-host$ WINEPREFIX=/home/gemini/.wine64 ./wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/hangover-git/build/wine-guest32/programs/notepad/notepad.exe 
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
32 bit environment set up, Large Address Aware: NO.
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_sprintf Calling host msvcrt instead of ntdll for now.
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
Not supported on foreign thread yet.
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\uxtheme.dll", setting to 0x78b6fcb9a0
Not supported on foreign thread yet.
Segmentation fault

**Comment by stefand** [comment]
> Not supported on foreign thread yet.
Your wrapper DLLs are out of sync with qemu's qemu_ops structure. I'm sorry to break the bad news to you, but you'll have to rebuild. It might be enough to remove build/dlls32 and build/dlls64 and run make in the top level directory. That is about 5% of the total build time, so it should be reasonably fast. If it doesn't make, remove the entire build/ directory and re-build.

Yes, the build system has a lot of bugs and missing dependency tracking. Patches are welcome.

Hangover takes a long time to build because it is building 3 builds of Wine - one for the aarch64 host, one for the x86 guest DLLs and one for the x86_64 guest DLLs. I usually do a fresh rebuild over night. After a Wine update trying to do an incremental build usually won't save you any time because a single change to a low level Wine header (e.g. winbase.h or winternl.h) will force a re-build of all 3 Wines. An incremental build in this situation will just make you run into obscure bugs of my top level hangover Makefile.

**Comment by cam1965** [comment]
Thank you so much.
Compiled again , but used -j8. ( much faster ). Removed build and compiled everything . The old notepad++ worked.Almost  of compiled apps from hangover , including notepad.exe worked.
But notepad++ 7.8.6 ( 32 and 64 bit  )  didn't work. Please see below

gemini@cosmopda:~$ WINEPREFIX=/home/gemini/.wine64 /home/gemini/hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/Downloads/npp7.8.6/notepad++.exe 
001b:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
000f:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
32 bit environment set up, Large Address Aware: NO.
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\WINTRUST.dll", setting to 0x7ee4ee09a0
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_sprintf Calling host msvcrt instead of ntdll for now.
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrLockLoaderLock Unverified!
0009:fixme:qemu_ntdll:qemu_LdrUnlockLoaderLock Unverified!
0009:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.__stdio_common_vsscanf imported from L"C:\\windows\\system32\\uxtheme.dll", setting to 0x7ee4ee09a0
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtQueryInformationProcess Unverified!
0009:fixme:qemu_ntdll:qemu_NtSetInformationProcess Unverified!

**Comment by AndreRH** [comment]
This sounds like #71

**Comment by AndreRH** [comment]
irrelevant with new Hangover approach
