### ISSUE TITLE
Error Prince of Persia 3d linux arm64 on cosmo communicator

### ISSUE THREAD

**Issue by cam1965** [AndreRH/hangover#67]
Hi.
I have installed Prince of Persia 3d on my arm64 linux running on cosmo communicator. The game was installed successful. But when I have tied to run this mesaage below has appeared. Please help me . Thanks.

gemini@cosmopda:~$ /home/gemini/hangover-git/build/wine-host/loader/wine64 /home/gemini/hangover-git/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /home/gemini/.wine/drive_c/Program\ Files/Prince\ of\ Persia\ 3D/pop3d.exe 
32 bit environment set up, Large Address Aware: NO.
0009:fixme:qemu_ntdll:qemu_LdrDisableThreadCalloutsForDll Unverified!
0009:fixme:qemu_ntdll:qemu_RtlUnicodeStringToAnsiString Unverified!
0009:err:qemu_msvcrt:qemu_init_dll loaded 0x7212210000
0009:fixme:qemu_ntdll:qemu_LdrGetProcedureAddress Unverified!
0009:fixme:qemu_ntdll:qemu_LdrGetProcedureAddress Unverified!
0009:fixme:qemu_ntdll:qemu_LdrDisableThreadCalloutsForDll Unverified!
0009:fixme:qemu_kernel32:qemu_MapViewOfFileEx Unverified!
gemini@cosmopda:~$

**Comment by AndreRH** [comment]
What's the status on this?

**Comment by AndreRH** [comment]
Please try again with modern Hangover
