### ISSUE TITLE
I can not run the program from third website

### ISSUE THREAD

**Issue by GitSoftwareNow** [AndreRH/hangover#73]
On the aarch64 platform,when I run ./wine64 /home/kylin/WeChatSetup.exe but the console says
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
0024:err:module:__wine_process_init L"G:\\home\\kylin\\WeChatSetup.exe" not supported on this system?

Is this a bug? How can I resolve?

**Comment by AndreRH** [comment]
You have to run WeChat through qemu, see https://github.com/AndreRH/hangover#4-how-to-run

**Comment by GitSoftwareNow** [comment]
@AndreRH 

./wine64 /root/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /root/.wine/drive_c/windows/system32/WeChatSetup.exe 
0050:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.
0078:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b8:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b8:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b8:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b8:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
Did not manage to load any host DLLs.
Failed to load host DLLs

**Comment by AndreRH** [comment]
Never run Wine as root! Also system32 is a weird place for a setup.exe
Did you build the host dlls?

**Comment by GitSoftwareNow** [comment]
how can I build host dlls?

**Comment by stefand** [comment]
They should be built when you run make in the top level directory. In other words, please make sure that hangover was built correctly.
