### ISSUE TITLE
An issue of run windows program

### ISSUE THREAD

**Issue by GitSoftwareNow** [AndreRH/hangover#74]
./wine64 /root/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /root/.wine/drive_c/windows/system32/WeChatSetup.exe
0050:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.
0078:err:ntoskrnl:ZwLoadDriver failed to create driver L"\Registry\Machine\System\CurrentControlSet\Services\wineusb": c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b0:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b8:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b8:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b8:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b8:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
Did not manage to load any host DLLs.
Failed to load host DLLs

what's the reason?

**Comment by AndreRH** [comment]
stop spamming
