### ISSUE TITLE
Run any programe error with aarch64 boards ubuntu

### ISSUE THREAD

**Issue by GitSoftwareNow** [AndreRH/hangover#78]
here is some logs

root@kylin-F120:~/hangover/build/wine-host/loader# ./wine64 /root/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so /root/wintest/WeChat/WeChat.exe 
0050:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0080:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
00ac:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00ac:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b4:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b4:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00b4:fixme:file:server_ioctl_file Unsupported ioctl 24000 (device=2 access=1 func=0 method=0)
00bc:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0024:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0024:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0024:err:qemu_riched20:qemu_dll_register Failed to instantiate a RICHEDIT_CLASS20A window.
0024:err:qemu_riched20:qemu_dll_register Failed to set WNDPROC of RICHEDIT_CLASS20A.
0024:err:qemu_riched20:qemu_dll_register Failed to instantiate a RichEdit50A window.
0024:err:qemu_riched20:qemu_dll_register Failed to instantiate a RICHEDIT_CLASS20W window.
0024:err:qemu_riched20:qemu_dll_register Failed to set WNDPROC of RICHEDIT_CLASS20W.
0024:err:qemu_riched20:qemu_dll_register Failed to instantiate a MSFTEDIT_CLASS window.
0024:err:secur32:SECUR32_initSchannelSP TLS library not found, SSL connections will fail
0024:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
32 bit environment set up, Large Address Aware: NO.
0024:fixme:qemu_kernel32:qemu_Wow64DisableWow64FsRedirection Unverified!
0024:fixme:qemu_kernel32:qemu_Wow64RevertWow64FsRedirection Unverified!
0024:fixme:qemu_kernel32:qemu_Wow64DisableWow64FsRedirection Unverified!
0024:fixme:qemu_kernel32:qemu_Wow64RevertWow64FsRedirection Unverified!
0024:fixme:qemu_kernel32:qemu_Wow64DisableWow64FsRedirection Unverified!
0024:fixme:qemu_kernel32:qemu_Wow64RevertWow64FsRedirection Unverified!
0024:fixme:qemu_module:import_dll No implementation for ucrtbase.dll._wopen imported from L"C:\\windows\\system32\\SETUPAPI.dll", setting to 0xffff980a92c8
0024:err:qemu_module:import_dll Library SSLEAY32.dll (which is needed by L"F:\\root\\wintest\\WeChat\\WeChatWin.dll") not found
0024:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.erf imported from L"C:\\windows\\system32\\gdiplus.dll", setting to 0xffff980a92c8
0024:fixme:qemu_module:import_dll No implementation for ucrtbase.dll.fmax imported from L"C:\\windows\\system32\\gdiplus.dll", setting to 0xffff980a92c8
0024:fixme:qemu_module:import_dll No implementation for kernel32.dll.K32GetWsChangesEx imported from L"C:\\windows\\system32\\PSAPI.DLL", setting to 0xffff980a92c8
0024:err:qemu_module:import_dll Library VoipEngine.dll (which is needed by L"F:\\root\\wintest\\WeChat\\WeChatWin.dll") not found
0024:err:qemu_module:import_dll Library libFFmpeg.dll (which is needed by L"F:\\root\\wintest\\WeChat\\WeChatWin.dll") not found
0024:err:qemu_kernel32:qemu_UnhandledExceptionFilter Application filter (nil).

**Comment by AndreRH** [comment]
What's the status on this?

**Comment by AndreRH** [comment]
irrelevant with new Hangover approach
