### ISSUE TITLE
configure: error: FreeType development files not found. Fonts will not be built.

### ISSUE THREAD

**Issue by farside268** [AndreRH/hangover#79]
Compiling on Buster in a crostini container. libfreetype6 and libfreetype6-dev are both installed.

**Comment by stefand** [comment]
Try to build plain wine from wine git. I expect it to fail in the same way. Look in config.log for debug info. If wine builds but hangover still fails please attach build/wine-host/config.log

Am 28. August 2020 01:21:10 GMT+03:00 schrieb farside268 <notifications@github.com>:
>Compiling on Buster in a crostini container. libfreetype6 and
>libfreetype6-dev are both installed.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AndreRH/hangover/issues/79

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by AndrePuls** [comment]
> 
> 
> Compiling on Buster in a crostini container. libfreetype6 and libfreetype6-dev are both installed.

1) I also have libfreetype6 installed (not sure if it make the difference):

2) Make sure, that you have the amd64 package installed and not the i386:
`apt list | grep freetype | grep installed`
gives on my Ubuntu Server:
`libfreetype-dev/focal,now 2.10.1-2 **amd64** [installed,automatic]
libfreetype6-dev/focal,now 2.10.1-2 **amd64** [installed]
libfreetype6/focal,now 2.10.1-2 **amd64** [installed,automatic]`

If you have a i386 package, remove it:
`apt purge libfreetype-dev:i386 libfreetype6-dev:i386 libfreetype6:i386
apt install libfreetype-dev:amd64 libfreetype6-dev:amd64 libfreetype6:amd64 `

if that doesn't help, use brute force:
`apt-get build-dep wine64`

if that doesn't help either, then you need to spend more than just 5 seconds and write a detailed error report. With properly structured sentences, actual commands you use and every piece of information, that may or may not be relevant.

**Comment by AndreRH** [comment]
Can we close this issue?

**Comment by farside268** [comment]
Sure. I haven't had time to follow up.
