### ISSUE TITLE
Make available for download on Raspbian

### ISSUE THREAD

**Issue by DonFlymoor** [AndreRH/hangover#82]
I don't have the bandwidth to download this extremely large repository and it's submodules on a RBPI 4. I would love to see this available in Raspbian 64 bit mirror, so that it can be installed with the command `apt install hangover`. I release that this may not be feasible, but if you could at least provide a compiled version, I would be grateful.

**Comment by AndreRH** [comment]
If hangover ever leaves it's alpha state we can consider this, but patches welcome to use e.g. https://build.opensuse.org/

**Comment by AndreRH** [comment]
Downloads are available by now
