### ISSUE TITLE
Pick up the now dead Exagear

### ISSUE THREAD

**Issue by Destroyer5150** [AndreRH/hangover#83]
Found this https://github.com/khanhduytran0/exagear_windows_emulator it's supposed to be the decompiled source code for Exagear. May or may not be helpful. It runs diablo 2 at full speed but Warcraft 3 at 10 fps at most. That's all I need now to make this phone the perfect old school emulator machine lol.

**Comment by stefand** [comment]
We are not going to look at code that violates copyright of others.
