### ISSUE TITLE
wine-host build fails - "configure: error: You need clang >= 5.0 to build Wine for arm64." during make

### ISSUE THREAD

**Issue by pseudofunizer** [AndreRH/hangover#84]
Just noticed that the latest Hangover versions give me that output when I'm trying to `make` the WINE part of Hangover on Ubuntu 20.04.1LTS, 64-bit on Raspberry Pi 4B.

Usually, when you are building `wine` on ARM64, this is a very typical error that I've encountered pretty much every time when trying to compile WINE from the Git source. On RPi4B & Ubuntu, I've solved things this way:

Go to the `wine` git directory:
`cd wine`

In order to bypass the clang-error, you need to type in:

`export CC=clang`
`export CXX=clang`
`export CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib"`

Then run configure:
`./configure` 

That should run without errors, if so, then proceed with `make`.

`make -j4` 

... However, when compiling WINE under Hangover, the CC/CXX/CFLAGS functions don't work in order to compile WINE as a functional part of Hangover as intended, even if if I've compiled it successfully from the source under the Hangover git tree.

Under Hangover's `make -j4` I always get the `configure: error: You need clang >= 5.0 to build Wine for arm64.` -error and Hangover's `make` build exits with `*** [Makefile: 115: build/wine-host/Makefile] Error 1`.

Any ideas?

**Comment by stefand** [comment]
yeah our makefile has HANGOVER_WINE_CC and HANGOVER_WINE_CXX for this. Just set those to clang and clang++ respectively and it will pass the right thing to wine-host but not screw up the other builds.

**Comment by pseudofunizer** [comment]
> 
> 
> yeah our makefile has HANGOVER_WINE_CC and HANGOVER_WINE_CXX for this. Just set those to clang and clang++ respectively and it will pass the right thing to wine-host but not screw up the other builds.

Thanks a lot for the reply. The compile worked way past that problem point by changing those settings, but now I ended up with another compile problem later on in the process -- specifically with QEMU (I left an issue ticket at https://github.com/AndreRH/hangover/issues/85 ). Thank you.

**Comment by tslgithub** [comment]
I have alse meet the error of "clang >- 5.0". Can you tell me how to   change "HANGOVER_WINE_CC"?

**Comment by tslgithub** [comment]
# Build the Host (e.g. arm64) wine.
# FIXME: If $HANGOVER_WINE_CC is not set this will define CC to an empty string, which still makes configure
# happy. Is there a nicer way?
build/wine-host/Makefile: wine/configure build/wine-tools/.built
        @mkdir -p $(@D)
        cd build/wine-host ; CC=$(HANGOVER_WINE_CC) CXX=$(HANGOVER_WINE_CXX) ../../wine/configure --with-wine-tools=../wine-tools $(ARCHFLAG_HOST) $(TESTS) $(CROSS_TRIPLE_H)



Should  I chang Makefile file  in  here？？？？？？？？

**Comment by stefand** [comment]
HANGOVER_WINE_CC=clang HANGOVER_WINE_CXX=clang++ make

If you don't know how to set an environment variable on the Linux shell it is unlikely that you'll be happy with hangover though. It is in a very early state and not ready for end users.

Delete build/wine-host before you run the above command to make sure configure is re-run
