### ISSUE TITLE
Question: Any plans to support PPC (32bit)?

### ISSUE THREAD

**Issue by thecatalinstan** [AndreRH/hangover#89]
... for us retro Mac enthusiasts. I could see my old G4 PowerBook running some old-timey Win32 apps.

I have no idea if any version of Wine (let alone the one hangover uses) even supports `ppc`.

**Comment by AndreRH** [comment]
Well, you are a bit late :)
Until recently Wine had PPC32 support which was abandoned because of **no users** and bitrot.
It still wouldn't be too hard to make a hangover spin yourself capable of PPC32, just use an older Wine and add very small assembler snippets in two places.
