### ISSUE TITLE
qemu tree not exists

### ISSUE THREAD

**Issue by fallenworld** [AndreRH/hangover#9]
When I run "git submodule update", error occurs:

fatal: reference is not a tree: efdfc3c9456e264f36e8014ca1bdf906ae9917b6
Unable to checkout 'efdfc3c9456e264f36e8014ca1bdf906ae9917b6' in submodule path 'qemu'

Also, if I click "qemu" on the hangover github page, it will shows "Page not found".

**Comment by stefand** [comment]
I forgot to push the qemu submodule again :-\ . It shoukd be fixed now.
