### ISSUE TITLE
it looks like wine32 is missing, you should install it.

### ISSUE THREAD

**Issue by tslgithub** [AndreRH/hangover#93]
firefly@firefly:~/hangover$ wine notepad
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
Could not load wine-gecko. HTML rendering will be disabled.
librga:RGA_GET_VERSION:3.02,3.020000 
ctx=0x81f4e570,ctx->rgaFd=11 
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32"
Could not load wine-gecko. HTML rendering will be disabled.
librga:RGA_GET_VERSION:3.02,3.020000 
ctx=0xb657a6e0,ctx->rgaFd=10 
wine: configuration in '/home/firefly/.wine' has been updated.

it looks like "wine32" is missing, but I can not install wine32 with "sudo apt-get install wine32" . Can you give me some advice?
Thank you very much.

**Comment by AndreRH** [comment]
You are trying to use alpha software but lack basic shell knowledge and didn't read the readme -> closing
