### ISSUE TITLE
libiconv no picking mingw-w64 crosscompiler, but clang

### ISSUE THREAD

**Issue by Chaosdave34** [AndreRH/hangover#99]
I have installed clang 5.0 from precompiled binaries (llvm.org). But when I run ./configure --enable-win64 I get the following error: "configure: error: You need clang >= 5.0 to build Wine for arm64."

Running on Raspberry Pi 4 Ubuntu 20.10 aarch64.

**Comment by AndreRH** [comment]
See #84

**Comment by Chaosdave34** [comment]
I keep getting the following error:

```
make[2]: Entering directory '/home/david/Workspace/hangover/build/libiconv32/src'
/bin/bash ../libtool --mode=link clang  -g -O2 iconv_no_i18n.o ../srclib/libicrt.a ../lib/libiconv.la iconv.res -o iconv_no_i18n
libtool: link: clang -g -O2 iconv_no_i18n.o iconv.res -o iconv_no_i18n  ../srclib/libicrt.a ../lib/.libs/libiconv.a
libtool: link: clang -g -O2 iconv_no_i18n.o iconv.res -o iconv_no_i18n  ../srclib/libicrt.a ../lib/.libs/libiconv.a
iconv.resiconv.res: file not recognized: file format not recognized
: file not recognized: file format not recognized
clangclang: : error: linker command failed with exit code 1 (use -v to see invocation)error
: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:78: iconv_no_i18n] Error 1
make[2]: *** [Makefile:78: iconv_no_i18n] Error 1
make[2]: Leaving directory '/home/david/Workspace/hangover/build/libiconv32/src'
make[2]: Leaving directory '/home/david/Workspace/hangover/build/libiconv64/src'
make[1]: *** [Makefile:56: install] Error 2
make[1]: Leaving directory '/home/david/Workspace/hangover/build/libiconv64'
make[1]: *** [Makefile:56: install] Error 2
make[1]: Leaving directory '/home/david/Workspace/hangover/build/libiconv32'
make: *** [Makefile:80: build/x86_64-w64-mingw32/bin/libcharset-1.dll] Error 2
make: *** Waiting for unfinished jobs....
make: *** [Makefile:76: build/i686-w64-mingw32/bin/libcharset-1.dll] Error 2
```

**Comment by AndreRH** [comment]
when libtool is using clang here it should use i686-w64-mingw32-gcc, is that installed? Please https://github.com/AndreRH/hangover/blob/master/README.md

**Comment by Chaosdave34** [comment]
I think it is installed. (I also have a package installed which is named win-iocnv-mingw or something like that)

**Comment by HoSnoopy** [comment]
i686-w64-mingw32-gcc is installed and executable.

**Comment by stefand** [comment]
you need x86_64-w64-mingw32 too

**Comment by HoSnoopy** [comment]
x86_64-w64-mingw32-gcc is also installed and executable.

**Comment by AndreRH** [comment]
What does config.log say, why are the mingw compilers not picked up?

**Comment by HoSnoopy** [comment]
Ah, no. It doesnt pick up. Debian Buster/ARM64 . Do I need aarch64_64-mingw32 something? I cannot find in the repo.

**Comment by AndreRH** [comment]
x86_64-w64-mingw32-gcc (exactly this name)
i686-w64-mingw32-gcc (exactly this name)

they are used to produce x86(_64) PE files, so no, you don't need an aarch64 version

could you pastebin the config.log please?

**Comment by HoSnoopy** [comment]
https://paste2.org/JUDZ42jF

**Comment by stefand** [comment]
This is wine's config.log, not libiconv

**Comment by stefand** [comment]
Hmm, did you maybe set CC=clang instead of HANGOVER_WINE_CC=clang?

**Comment by Chaosdave34** [comment]
https://paste2.org/EKhNHOUO
libiconv config.log

**Comment by stefand** [comment]
ew yeah, libiconv needs different configure arguments. Delete the build/*libiconv* folders and let the top level makefile do its job, or look in the top level makefile for the exact arguments (it sets the host to i686 mingw / x86_64 mingw and the install prefix to a private folder in build/ etc)

**Comment by Chaosdave34** [comment]
Its still the same Error, nothing changed.

**Comment by Chaosdave34** [comment]
Now libiconv workd but now qemu makes problems:
`make -C build/qemu
make[1]: Verzeichnis „/home/pi/Workspace/hangover/build/qemu“ wird betreten
make[1]: *** Keine Ziele.  Schluss.
make[1]: Verzeichnis „/home/pi/Workspace/hangover/build/qemu“ wird verlassen
make: *** [Makefile:183: build/qemu/x86_64-windows-user/qemu-x86_64.exe.so] Fehler 2
`

**Comment by AndreRH** [comment]
irrelevant with new Hangover approach
